/**
 * Archetype quote engine (spec §3.3–3.4).
 * Each archetype has lines for 6 moment types. The engine fires them contextually.
 */

import { commanderIsAlive, resolveVoiceLeader } from "./ranks";
import type { CrewMember, GameState, PlaySub } from "../engine/types";

export type QuoteMoment =
  | "start"       // Mission start / briefing
  | "combat"      // During a fight
  | "down"        // After taking damage / crew loss
  | "win"         // After a good tier outcome
  | "tired"       // Low constitution (< 40)
  | "death";      // Crew death narrative

export type Archetype =
  | "veteran"
  | "kid"
  | "dark_comedian"
  | "pragmatist"
  | "faithful"
  | "angry_one"
  | "quiet_one"
  | "homesick_one"
  | "glory_hound"
  | "cynical_one"
  | "natural"
  | "old_hand"
  | "reluctant_one"
  | "protector"
  | "displaced";

type QuoteTable = Record<QuoteMoment, string[]>;

export const QUOTE_ARCHETYPES = [
  "veteran",
  "kid",
  "dark_comedian",
  "pragmatist",
  "faithful",
  "angry_one",
  "quiet_one",
  "homesick_one",
  "glory_hound",
  "cynical_one",
  "natural",
  "old_hand",
  "reluctant_one",
  "protector",
  "displaced",
] as const satisfies readonly Archetype[];

export const QUOTE_MOMENTS = [
  "start",
  "combat",
  "down",
  "win",
  "tired",
  "death",
] as const satisfies readonly QuoteMoment[];

const QUOTES: Record<Archetype, QuoteTable> = {
  veteran: {
    start: [
      "We do this clean. No heroics.",
      "Same road, different names on the map.",
      "I've seen this before. That's not reassuring.",
      "Know your exits before you need them.",
      "Trust the plan until the plan breaks. Then trust each other.",
      "We move when I say move. Not before.",
      "The road teaches you what the briefing forgot.",
      "If we're arguing, we're still alive. Argue fast.",
    ],
    combat: [
      "Stay calm. Fear spends bullets.",
      "Don't let them know you're scared. They're scared too.",
      "Keep your head low and your eyes open.",
      "Short bursts. Pick your shots.",
      "Breathe. You can panic after.",
      "First man who runs takes the round. Stay put.",
      "Count the muzzle flashes. That's the real math.",
      "Steady hands beat brave ones.",
    ],
    down: [
      "We've taken worse.",
      "Walk it off. The road keeps going.",
      "It hurts because it's real. Real means you're still here.",
      "Count what you've got left. Then use it.",
      "Pain is data. Process it and move.",
      "This isn't the worst day. I've had worse days.",
      "Shake it off. The crew needs you upright.",
      "Pain passes. Panic doesn't help anyone.",
    ],
    win: [
      "Good. Don't get used to it.",
      "That's how it's done.",
      "Clean work. Keep moving.",
      "File it and move. Next problem.",
      "Better than expected. Still not done.",
      "Take thirty seconds. Then we're back to work.",
      "Clean enough. Don't get sentimental about it.",
      "We earned the breathing room. Use it fast.",
    ],
    tired: [
      "I'm running on procedure. That's fine.",
      "Sleep is for the other side of this.",
      "Tired is normal. Dead is worse.",
      "Worn is not broken.",
      "I've fought tired before. I'll fight tired again.",
      "The body complains. Ignore it.",
      "Coffee would help. So would sleep. Neither is coming.",
      "I've been tired since before this road started.",
    ],
    death: [
      "He knew what this was. He came anyway.",
      "Write it down when you get a minute.",
      "Remember the name. Forget the rest.",
      "He did his job. We do ours.",
      "Don't mourn now. Mourn when you're safe.",
      "He was good at this. That's the honest eulogy.",
      "The crew goes on. That's the only tribute that counts.",
      "Say the name once. Then get back to work.",
    ],
  },
  kid: {
    start: [
      "I'm ready. I'm ready. I'm ready.",
      "Just tell me what to do and I'll do it.",
      "I looked at the map. I understand it now. I think.",
      "I've trained for this. I think I've trained for this.",
      "Is everyone else this nervous or is it just me.",
      "I'm not scared. I'm just— yes I am. A little.",
      "Tell me the plan again. Slower this time.",
      "I'll do my part. I promise I'll do my part.",
    ],
    combat: [
      "Is it supposed to be this loud?",
      "Tell me what to do. Just tell me what to do.",
      "I'm doing it. I'm doing the thing.",
      "Okay. Okay. Okay. Okay.",
      "There's so many of them—okay. Okay.",
      "I can do this. I can do this.",
      "My hands won't stop shaking. I'll hide that.",
      "Someone said my name. I'm still here.",
    ],
    down: [
      "I didn't think it'd—I didn't—",
      "Is everyone okay? Tell me everyone's okay.",
      "I can keep going. Tell me I can keep going.",
      "That was real. That was a real thing that just happened.",
      "Nobody told me it would feel like this.",
      "I want to sit down. I can't sit down. Okay.",
      "That was real. I'm still here. That's something.",
      "Don't look at me like that. I'm fine. I'm fine.",
    ],
    win: [
      "We did it. Holy— we did it.",
      "I didn't die. I didn't die!",
      "That was... okay. That was okay.",
      "I helped. I actually helped.",
      "We're still alive. That's great. That is great.",
      "Can we do that again? No. Yes. Maybe.",
      "Still here. Still here. Still here.",
      "Tell me that counted for something.",
    ],
    tired: [
      "I'm fine. I'm just tired.",
      "How do you sleep? I can't sleep.",
      "Does it get easier? Don't answer that.",
      "I haven't slept since we left.",
      "I keep seeing things when I close my eyes.",
      "I thought tired was normal. This isn't normal tired.",
      "I keep counting hours until I can sleep.",
      "My eyes burn. I still have to see.",
    ],
    death: [
      "He was scared the whole time. He never said.",
      "He was going to write to his mother.",
      "He was twenty-two. I thought he was younger.",
      "He was laughing this morning.",
      "I don't know what to say. I don't know what you say.",
      "He was the one who explained things to me. I don't know who I ask now.",
      "He was younger than the war. That's the part that sticks.",
      "I didn't know how to say goodbye. I still don't.",
    ],
  },
  dark_comedian: {
    start: [
      "Another chance to become a footnote.",
      "I've done worse for worse reasons.",
      "The briefing was optimistic. I love optimism.",
      "On the bright side, none of this matters historically.",
      "You know what this reminds me of? Every other disaster I've been in.",
      "The odds are terrible. The company's decent. Let's go.",
      "If we die, at least the paperwork will be funny.",
      "Morale is a suggestion. I'm ignoring it.",
    ],
    combat: [
      "Exciting. In all the wrong ways.",
      "This is fine. Burning is fine. We're fine.",
      "Fun fact: nobody's watching and nobody cares. Move.",
      "I've been in worse situations. I can't remember when, but I have.",
      "Truly a fantastic place to get shot at.",
      "If we make it through this, I have a very good story.",
      "Morale is a joke. I'm telling it.",
      "We're not heroes. We're receipts.",
    ],
    down: [
      "Well. That happened.",
      "We're doing great. Comparatively.",
      "The bar was low. We're under it. Still breathing.",
      "Noted for the memoir I will definitely write.",
      "Could be worse. In ways I won't specify.",
      "Oh, so that's what that feels like.",
      "Pain is temporary. Embarrassment is forever.",
      "I've had worse Tuesdays. This ranks high though.",
    ],
    win: [
      "Survival is its own comedy.",
      "Huh. Didn't see that coming.",
      "Against all reasonable odds.",
      "The universe blinked. Let's move before it looks again.",
      "That went better than statistically likely.",
      "Someone's laughing at us. At least we're entertaining.",
      "I'll take the win. I won't trust it.",
      "That was improbable. I love improbable.",
    ],
    tired: [
      "I'm medically tired. It's fine.",
      "Sleep is a myth propagated by the living.",
      "Running on spite and historical irony.",
      "I've given up on sleep. We have an arrangement.",
      "My body's filing a grievance. I declined to hear it.",
      "At this point I'm basically a ghost who complains.",
      "Coffee is a religion. I am devout.",
      "If I sit down I might never stand up. Classic problem.",
    ],
    death: [
      "He'd have made a joke about this.",
      "He always said he'd die doing something stupid. He was half right.",
      "He was funnier than me. Don't tell anyone I said that.",
      "He would have hated the ceremony. He's getting one anyway.",
      "He called it. I didn't believe him. He called it.",
      "He'd want us to laugh eventually. Not yet. But eventually.",
      "He made the war smaller for a minute. That was his gift.",
      "Tell the story right. He'd hate a boring ending.",
    ],
  },
  pragmatist: {
    start: [
      "Objective, route, resources. We have all three.",
      "Let's not waste time.",
      "The math works out. For now.",
      "I've identified three failure points. I'm watching all of them.",
      "No improvisation unless the plan breaks. The plan won't break.",
      "Contingency is already in the route. Don't deviate.",
      "Variables are manageable. Panic is not a variable.",
      "We proceed on schedule. Adjust only with data.",
    ],
    combat: [
      "Ammo count, angles, priority. Focus.",
      "Emotion is overhead. Cut it.",
      "The right choice is the one that costs less.",
      "Maximize output, minimize exposure. It's not complicated.",
      "Identify the target. Engage. Move.",
      "Don't shoot until you're sure. Sure takes a second.",
      "Suppress emotion. Execute the sequence.",
      "Efficiency saves lives. Waste costs them.",
    ],
    down: [
      "Damage assessment. What do we have left?",
      "Inventory what works. Discard what doesn't.",
      "Losses happen. What's the recovery path?",
      "Recalculate from current position.",
      "Setback is data. Process and continue.",
      "We work with what remains.",
      "Damage logged. Mitigation in progress.",
      "The setback is quantified. We adapt.",
    ],
    win: [
      "Expected outcome. Moving on.",
      "Efficient. Good.",
      "That worked. File it.",
      "Confirm all objectives. Then move.",
      "Within projected parameters.",
      "Functional result. Log and continue.",
      "Outcome acceptable. Proceed.",
      "No anomalies. Continue mission.",
    ],
    tired: [
      "Fatigue is a variable. I'm accounting for it.",
      "I'll rest when the numbers allow.",
      "Tired means inefficient. Push through.",
      "Reduced capacity noted. Adjusting output expectations.",
      "I function adequately below optimal.",
      "Sleep will be scheduled. After this.",
      "Reduced sleep increases error rate. I compensate.",
      "Fatigue noted. Performance within tolerance.",
    ],
    death: [
      "The mission continues. That's what he would want.",
      "He was reliable. Reliable people are rare.",
      "Account for the gap. Fill it.",
      "Loss creates a deficit. We cover it.",
      "He performed every task assigned to him. Record that.",
      "The mission requires continuation. He would agree.",
      "Replace the function. Honor the record.",
      "His slot is empty. The work is not.",
    ],
  },
  faithful: {
    start: [
      "Whatever comes, we're not alone in it.",
      "I don't know His plan. I show up anyway.",
      "Light enough to see the next step.",
      "I've said my piece. Now I work.",
      "Something larger is at stake. I feel it.",
      "I trust the hands I can't see. And the ones beside me.",
      "I've prayed for worse mornings than this.",
      "We walk forward. That's the whole sermon.",
    ],
    combat: [
      "Keep your head down and your heart up.",
      "Fear is honest. Faith is choosing to move anyway.",
      "Somebody's watching. Might as well do it right.",
      "Courage isn't the absence of fear. I know that now.",
      "I move through this because I have to. Something carries me.",
      "Lord of hosts. Help us.",
      "Mercy in the middle of the noise. I ask for that.",
      "Fear is honest. So is faith.",
    ],
    down: [
      "Still here. That means something.",
      "I've prayed in worse positions.",
      "Grace shows up in foxholes. I've seen it.",
      "We are not abandoned. I hold to that.",
      "I don't understand this. I still believe.",
      "Something is being asked of us. We answer.",
      "Grace in the middle of the mess. I felt it.",
      "Still breathing. Still believing.",
    ],
    win: [
      "Thank you. Moving on.",
      "Someone was watching out.",
      "Not luck. I don't believe in luck.",
      "Gratitude. Then back to work.",
      "Given to us. Not owed to us.",
      "I said a word of thanks already. Let's go.",
      "Given breath. Given time. Use both well.",
      "Not luck. I won't call it luck.",
    ],
    tired: [
      "Tired is honest. I'll rest on the other side of this.",
      "I'm leaning on something you can't see.",
      "Prayer is work. Work is prayer.",
      "My body asks for rest. I ask for just a little more.",
      "Weary doesn't mean faithless.",
      "Even this—even this is part of something.",
      "Weariness is not the same as despair.",
      "I lean on what I cannot see.",
    ],
    death: [
      "He's somewhere better than this. I have to believe that.",
      "We'll see him again. That's not comfort, it's conviction.",
      "He fought with everything he had. That counts.",
      "He was a good man. I believe good men are accounted for.",
      "I don't understand this. I choose to trust anyway.",
      "Rest now. Rest.",
      "His faith outlasted the fear. Remember that.",
      "Light enough for the next step. He took his.",
    ],
  },
  angry_one: {
    start: [
      "Good. Something to hit.",
      "Tell me the target. I'll handle the rest.",
      "I stopped being angry about this. I started being useful.",
      "I don't need a speech. Just point me at it.",
      "Every mission is a chance to settle a score. Let's go.",
      "I am exactly in the right mood for this.",
      "Point me at it. I'll do the rest.",
      "Anger is fuel. Tank's full.",
    ],
    combat: [
      "Harder. Push harder.",
      "COME ON.",
      "They want to stop us? Let them try.",
      "Don't slow down. Don't ever slow down.",
      "I will not stop. I will not stop.",
      "You want a fight? You've got one.",
      "Let them come. I'm ready.",
      "Rage clears the head. Use it.",
    ],
    down: [
      "You want to see angry? I'll show you angry.",
      "That's it? That's all you've got?",
      "I've been hit worse. By people I liked.",
      "Pain makes me faster. Try again.",
      "That just made me angrier. Bad call on their part.",
      "Not down. Not even close.",
      "That hurt. Good. Makes me sharper.",
      "Try again. I'll be here.",
    ],
    win: [
      "Good. Still standing.",
      "Yeah. That's right.",
      "More where that came from.",
      "That's what happens.",
      "Next.",
      "Don't celebrate. Keep the edge.",
      "Still here. Still dangerous.",
      "That's how it's done. Again.",
    ],
    tired: [
      "I don't get tired. I get focused.",
      "Anger keeps you warm.",
      "Sleep makes you soft. I'll sleep when this is over.",
      "Tired is a luxury. I'll pass.",
      "I'm running hot. That's fine. I prefer it.",
      "Rest? No. Not yet.",
      "Sleep is for after. Not during.",
      "The fire keeps me warm. I'll bank it.",
    ],
    death: [
      "He died mad at something. He was always mad at something. It kept him going.",
      "He'd want us to keep fighting. So we keep fighting.",
      "The anger outlasts the man. That's not nothing.",
      "He was the angriest man I knew. He was also the most alive.",
      "He went out swinging. That's the only way for a man like him.",
      "He fought it. He fought everything. He didn't quit.",
      "The anger kept him alive. It keeps us moving.",
      "He'd want the next round. Give it to him.",
    ],
  },
  quiet_one: {
    start: [
      "...",
      "Ready.",
      "Let's go.",
      "I heard the briefing.",
      "Understood.",
      "In position.",
      "Noted.",
      "Proceeding.",
    ],
    combat: [
      "On it.",
      "Covering.",
      "Moving.",
      "Clear.",
      "Contact.",
      "Engaging.",
      "Left.",
      "Right.",
    ],
    down: [
      "Still functional.",
      "Noted.",
      "We continue.",
      "Operational.",
      "Acknowledged.",
      "...",
      "Continuing.",
      "Affirmative.",
    ],
    win: [
      "Good.",
      "Next.",
      "...",
      "Done.",
      "Moving.",
      "Copy.",
      "Clear.",
      "Proceed.",
    ],
    tired: [
      "...",
      "Still here.",
      "Continuing.",
      "Functional.",
      "Affirmative.",
      "On watch.",
      "Awake.",
      "Present.",
    ],
    death: [
      "He didn't talk much. When he did, it meant something.",
      "The silences are different without him.",
      "...",
      "I keep turning to tell him something.",
      "He was always there. Now he isn't.",
      "I won't say anything. He'd understand.",
      "The quiet is louder now.",
      "He held the space. I'll try.",
    ],
  },
  homesick_one: {
    start: [
      "A hundred miles from anything I know.",
      "What I wouldn't give for a bad diner and good coffee.",
      "Starting to forget what home smells like.",
      "I keep a picture in my left breast pocket. I checked it this morning.",
      "Everything here is wrong in a hundred small ways.",
      "I'm doing this so I can go back. That's the whole story.",
      "Home is a direction. I keep facing it.",
      "The picture in my pocket is getting worn.",
    ],
    combat: [
      "Every shot puts me one closer to home. That's the math.",
      "I've got something to live for. That helps.",
      "I'm coming back. I'm coming back.",
      "Think of the porch. The light in the kitchen. Keep moving.",
      "Not here. Not today. I've got people waiting.",
      "I am going home. Nothing changes that.",
      "For the porch light. For whoever's waiting.",
      "One more mile toward familiar ground.",
    ],
    down: [
      "I keep thinking about the kitchen in the morning.",
      "I promised I'd come back in one piece.",
      "Not here. Not like this.",
      "I need to get home. I need to get home.",
      "I keep writing letters in my head that I never send.",
      "They don't know what this looks like. I can't explain it.",
      "I promised I'd come back. I mean it.",
      "Not here. Not like this. Not yet.",
    ],
    win: [
      "One more. Just keep adding one more.",
      "Getting closer.",
      "Still in the game.",
      "Still going home.",
      "I count every one. This is another one.",
      "That's a day closer. I'll take it.",
      "Another day. Count it.",
      "Still on the road home.",
    ],
    tired: [
      "I keep dreaming about the wrong things.",
      "Three more months. I can do three months.",
      "Home is a country I'm from.",
      "I've been away so long I wonder if it's changed.",
      "Tired is fine. I've been tired the whole time.",
      "I dream about ordinary things. Breakfast. The commute.",
      "Tired is fine if I'm still walking toward them.",
      "I smell rain like home sometimes. Then I don't.",
    ],
    death: [
      "He talked about home every day. Every single day.",
      "He was going to see his kid graduate.",
      "He never stopped hoping. That's not a weakness.",
      "He had a whole life planned out in his head. He showed me the map.",
      "He was almost done. He was almost through it.",
      "He never stopped writing letters home. Every chance he had.",
      "He was almost home in his head. That's where he lived.",
      "Send the letter. Tell them he tried.",
    ],
  },
  glory_hound: {
    start: [
      "This is the one. This is where it matters.",
      "I want a clean fight. Something they'll remember.",
      "Tell me the hardest part. I'll take it.",
      "History remembers the bold. I intend to be remembered.",
      "I didn't come here to watch. I came to be watched.",
      "If I'm going to do this, I'm going to do it loudly.",
      "Watch me work.",
      "This is the scene. I'm in it.",
    ],
    combat: [
      "Front and center. Every time.",
      "Watch this.",
      "I'll get the citation for this one.",
      "This is what I was built for.",
      "Someone take notes. I'm not doing this twice.",
      "I'll handle it. Someone write that down.",
      "Center stage. Always.",
      "They'll remember this beat.",
    ],
    down: [
      "That was not supposed to happen.",
      "I've had worse. In front of fewer witnesses.",
      "Not today. Not like this.",
      "I am not going out like this. I refuse.",
      "Setbacks are fine. Setbacks make the story better.",
      "Inconvenient. But not terminal.",
      "Not how the story ends. Not today.",
      "The audience isn't done watching.",
    ],
    win: [
      "That's what I'm talking about.",
      "Record that. Somebody record that.",
      "That's what they'll write about.",
      "I would like a full account submitted.",
      "That was the moment. I know when I'm in a moment.",
      "Remember where you were. This is the story.",
      "Citation material. Obviously.",
      "That's the headline. Write it.",
    ],
    tired: [
      "I'm fine. I look worse than I am.",
      "Pain is aesthetically inconvenient.",
      "Medals don't care if you slept.",
      "Exhaustion is for the uninspired.",
      "I look worse than I feel. Maybe the reverse. Either way.",
      "The legend doesn't get tired. The man does. I'm the legend today.",
      "Exhaustion is for the supporting cast.",
      "I'll sleep when the medals arrive.",
    ],
    death: [
      "He wanted to be remembered. I think he will be.",
      "He died doing exactly what he wanted to do. I don't know if that helps.",
      "He went out loud. He'd have wanted it that way.",
      "He would want the whole account. Every detail.",
      "He earned his story. Make sure it gets told right.",
      "He went out the way he lived. Bigger than the room.",
      "He wanted witnesses. He got them.",
      "Tell it loud. He'd hate a whisper.",
    ],
  },
  cynical_one: {
    start: [
      "The briefing was garbage and we all know it.",
      "We're doing this. Fine. Let's just do this.",
      "Another morning, another lie about the objective.",
      "Nobody asked me. Nobody asks me. Noted. Moving on.",
      "Low expectations are the key to spiritual survival.",
      "Optimism is a coping mechanism for people who haven't been here long.",
      "Another day. Another invoice from reality.",
      "Sure. Let's pretend this briefing was accurate.",
    ],
    combat: [
      "Expected.",
      "Nobody's surprised. Everyone keep moving.",
      "This is fine. This is how it always goes.",
      "Called it. Not happy about it.",
      "Every plan eventually meets the moment. Here we are.",
      "Complicated by design. Or by incompetence. No difference.",
      "Shocking. Truly shocking. Moving on.",
      "Nobody's impressed. Least of all me.",
    ],
    down: [
      "Yep.",
      "What did you expect?",
      "The plan failed. Make a new plan.",
      "I mean... yes. Of course.",
      "Listed under: things that were going to happen.",
      "Disappointment implies prior hope. I was fine.",
      "Predictable damage. Predictable response.",
      "Of course. Naturally.",
    ],
    win: [
      "Luck. Pure luck.",
      "Great. It'll get harder.",
      "That worked. Doesn't mean anything.",
      "Fine. Enjoy it. The next one'll balance the books.",
      "Don't read into this.",
      "It went well. I'll worry about why later.",
      "Fine. Don't get attached to fine.",
      "Temporary relief. Permanent skepticism.",
    ],
    tired: [
      "Tired is the honest reaction.",
      "I've stopped expecting it to get better.",
      "Fine. I'm fine. We're all fine.",
      "The exhaustion is appropriate.",
      "I've been tired longer than you've been here.",
      "I'd rest if I thought it would help.",
      "Exhaustion is the only honest forecast.",
      "Sleep won't fix the math. I'll skip it.",
    ],
    death: [
      "He deserved better. They all do.",
      "Add him to the list nobody reads.",
      "The war keeps going. That's the honest truth.",
      "The system that sent him here owes a debt it will never pay.",
      "He was worth more than this. The math never works out.",
      "Someone will send a letter. That's all.",
      "The war doesn't pause for grief. It never does.",
      "Add one more name. The list grows.",
    ],
  },
  natural: {
    start: [
      "I've got a feeling about this one.",
      "I know where they'll be. I can't explain how I know.",
      "This is what I do. Let's go.",
      "I read the ground before the briefing. I already know the problem.",
      "Don't overthink it. I've got the picture.",
      "Something's off. I'll watch the left flank.",
      "The ground's talking. I'm listening.",
      "Don't argue with the feeling. Follow it.",
    ],
    combat: [
      "I've got the angle. Trust me.",
      "I see it. I've always seen it.",
      "Follow my lead. Don't think. Go.",
      "Cover left. Don't ask why.",
      "The gap opened. Moving.",
      "I won't explain it. I'll show you.",
      "Trust the read. I always do.",
      "The angle's there. I see it.",
    ],
    down: [
      "Didn't see that one. Noted.",
      "I'll adapt. I always adapt.",
      "New situation, new solution.",
      "Recalibrate. I can work with this.",
      "The picture changed. I'm already updating it.",
      "Unexpected. I adjust.",
      "New data. New move.",
      "The picture shifted. I'm already there.",
    ],
    win: [
      "Told you.",
      "Not luck. Instinct.",
      "That's how it should go.",
      "I felt that coming from fifty meters out.",
      "The ground told me.",
      "When you know, you know.",
      "Read was right. Again.",
      "Instinct doesn't need applause.",
    ],
    tired: [
      "Tired doesn't slow down instinct.",
      "I run better without thinking.",
      "The less I'm in my head, the better.",
      "My body runs it. I stay out of the way.",
      "Sleep sharpens instinct. Lack of it doesn't dull it for me.",
      "I do my best work when I stop trying.",
      "Body tired. Sense isn't.",
      "I'll trust the gut until it quits.",
    ],
    death: [
      "He had good instincts. Better than mine, some days.",
      "He read ground the way some people read books.",
      "I'll miss watching how he moved.",
      "He always knew before the rest of us. I counted on that.",
      "He had a sense for it. That kind of sense doesn't come from training.",
      "He knew. He always knew a beat before everyone else.",
      "The crew will feel the gap. I already do.",
      "Read the ground for him once more.",
    ],
  },
  old_hand: {
    start: [
      "Done this before. I'll do it again.",
      "Nothing surprises me anymore. That's good and bad.",
      "The map's wrong. It's always wrong.",
      "Third time on a road like this. I know the rhythm.",
      "Every mission sounds the same at the beginning.",
      "I've been here before. Not here exactly. Close enough.",
      "Same road. Different craters.",
      "The rhythm hasn't changed. I have.",
    ],
    combat: [
      "Conserve. Everything. Always.",
      "We've been in tighter spots.",
      "Patience. Let them make the mistake.",
      "Wait for the second wave. There's always a second wave.",
      "Controlled. Measured. Breathe.",
      "I've been doing this longer than this war. It shows.",
      "Patience wins. Rush loses.",
      "Second wave's coming. Always is.",
    ],
    down: [
      "Walk it off. Done worse with less.",
      "I've been this tired before. Made it through.",
      "Calibrate and continue.",
      "Not the worst. Not even close.",
      "I've been hurt worse on a normal day.",
      "Still here. Still functional. That's the count.",
      "Seen worse. Survived worse.",
      "Shake it. Keep the pace.",
    ],
    win: [
      "Again. One more time.",
      "That's the way.",
      "Works every time. Sometimes.",
      "Same as always. Same as it'll be.",
      "Predictable. That's the goal.",
      "We've done harder. This was cleaner than expected.",
      "Same outcome as last time. Good.",
      "File it. Move on.",
    ],
    tired: [
      "I've been this tired since '42. Still here.",
      "Tired means experienced.",
      "Sleep is for people who haven't done this before.",
      "Tired is just the price.",
      "I'll sleep in a year. Maybe.",
      "I've operated on less. I know what I have left.",
      "Tired is the tariff. I pay it.",
      "Sleep's a rumor. I ignore rumors.",
    ],
    death: [
      "He made it this far. That's further than most.",
      "He knew the risks. He stayed anyway.",
      "I've lost better men. I've lost worse ones. It never stops costing.",
      "I don't get used to it. I just know what to do with it.",
      "He was good at the work. That's what I'll say.",
      "He lasted. Long enough to matter. That's something.",
      "I've buried better. I'll bury this one too.",
      "The road doesn't stop for names.",
    ],
  },
  reluctant_one: {
    start: [
      "If I had a choice. I don't. Moving on.",
      "I'm here. I didn't say I liked it.",
      "Let's get this over with.",
      "Noted: I would rather be anywhere else. Proceeding.",
      "I volunteered for nothing about this.",
      "The sooner it starts, the sooner it ends.",
      "Objection noted. Moving anyway.",
      "I'd rather be literally anywhere else.",
    ],
    combat: [
      "I hate this. Keep going. I hate this.",
      "I'm doing it. I'm not enjoying it.",
      "This was not what I signed up for. This is what I'm doing anyway.",
      "Objecting under protest. Still moving.",
      "I'd file a complaint if there was somewhere to send it.",
      "Continuing. Begrudgingly. Effectively.",
      "Still hate it. Still doing it.",
      "Protest continues. So do I.",
    ],
    down: [
      "Exactly what I expected.",
      "I didn't want this. It happened anyway.",
      "This is fine. Nothing is fine.",
      "Right on schedule with my expectations.",
      "I said from the beginning—but fine.",
      "No surprises. That's the one silver lining.",
      "Called it. Unfortunately.",
      "This tracks with my expectations.",
    ],
    win: [
      "There. Done. Happy?",
      "We survived. I'll reserve celebration.",
      "I'll allow it.",
      "Fine. Acceptable.",
      "I wasn't expecting that to work. It worked.",
      "Good. Can we go now.",
      "Survived. Unenthused. Present.",
      "Done. Next objection in five miles.",
    ],
    tired: [
      "Tired is appropriate given the circumstances.",
      "I'd like to be somewhere else. I'm here.",
      "Protest noted. Action continues.",
      "The fatigue is proportionate.",
      "I didn't sleep. That tracks.",
      "Everything I said I'd hate about this? All of it. Correct.",
      "Exhaustion is fair. I accept the invoice.",
      "I'd nap if the war allowed naps.",
    ],
    death: [
      "He didn't want this. He did it anyway. That's more courage than wanting to.",
      "He protested everything and showed up for everything.",
      "He complained about this place every day. He never left early.",
      "He hated it here. He never stopped doing the work.",
      "He grumbled every step of every mile. He never missed one.",
      "He didn't die for glory. He died because he stayed. That's different.",
      "He showed up anyway. Remember that.",
      "The complaint stopped. The courage didn't.",
    ],
  },
  protector: {
    start: [
      "Keep an eye on each other today.",
      "Whatever happens, we bring everyone back.",
      "I'm not losing anyone today.",
      "Eyes on your neighbors. The whole time.",
      "We move together. We leave together.",
      "You're my responsibility. All of you.",
      "I watch all of you. All the time.",
      "Nobody slips past me today.",
    ],
    combat: [
      "Stay together. No one breaks off.",
      "If they're going for the crew, they're going through me.",
      "Watch your arcs. Watch each other.",
      "No one gets left. No one.",
      "I've got your flank. Move.",
      "You're covered. Go.",
      "I've got the crew. Move.",
      "Eyes on every hatch.",
    ],
    down: [
      "Is everyone okay? Count off.",
      "Regroup. Check the crew.",
      "Someone get eyes on everyone.",
      "Head count. Now.",
      "I need to see everyone before we move.",
      "Nobody moves until I know everyone's status.",
      "Head count. Say your names.",
      "Status on everyone. Now.",
    ],
    win: [
      "Everyone's still here. Good.",
      "Count off. Good. We're good.",
      "That's what matters.",
      "All present. That's a win.",
      "We're all here. That's the only metric I track.",
      "You're all okay. That's the whole point.",
      "All accounted for. That's the win.",
      "Nobody missing. That's the metric.",
    ],
    tired: [
      "I can keep watch. Get some sleep.",
      "Tired means I'm still keeping watch.",
      "I'll rest when everyone else is okay.",
      "As long as they need watching, I'm watching.",
      "Sleep comes after I know they're safe.",
      "I don't put down the burden until everyone's down safe.",
      "They sleep. I watch.",
      "Tired is fine. Missing someone isn't.",
    ],
    death: [
      "I should have— I could have—",
      "He was my responsibility. I carry that.",
      "I'll make sure it means something.",
      "I keep running the math. I keep losing.",
      "There will never be a version where I'm okay with this.",
      "I'll carry him. I carry them all.",
      "My watch failed once. I won't forget.",
      "He was under my care. He still is.",
    ],
  },
  displaced: {
    start: [
      "I fight for something that doesn't exist anymore. That's fine.",
      "This isn't my country. These are still my people.",
      "I know what we're fighting for. I've already lost it.",
      "I've been moving since before this started. I haven't stopped.",
      "I have no home to go back to. That means I have nothing left to lose.",
      "I know what it looks like when a place is taken. I was there.",
      "Home is a word I don't use anymore.",
      "I fight for people who still have a when.",
    ],
    combat: [
      "I know what it looks like when it's gone. Fight harder.",
      "Every round is for the people who can't fight back.",
      "I've seen what they do. I know what I'm doing.",
      "I fight with memory. That's a different kind of fuel.",
      "They took everything else. They don't take this.",
      "For everyone left behind. Every one.",
      "Memory is ammunition. I have plenty.",
      "They won't take this from us too.",
    ],
    down: [
      "I've already lost more than this.",
      "It can always be worse. I've seen worse.",
      "Still standing. Still fighting.",
      "Pain is familiar. It doesn't stop me.",
      "I've grieved enough. This is nothing.",
      "I've survived worse beginnings than this middle.",
      "Pain I know. Fear I know. I keep moving.",
      "Worse has happened. I'm still standing.",
    ],
    win: [
      "For everyone who didn't get to see this.",
      "Small victory. Add it to the ledger.",
      "We move forward. We always move forward.",
      "One step back toward something worth having.",
      "For every place that's been taken. A reckoning.",
      "It doesn't undo anything. It's still worth doing.",
      "A small win for the lost places.",
      "Forward. Always forward.",
    ],
    tired: [
      "I carry tired like luggage. I don't put it down.",
      "The exhaustion is old. Doesn't mean I stop.",
      "I rest when the fight is done.",
      "I've been tired longer than the war has been going.",
      "I stopped expecting to feel rested. It freed up a lot of mental space.",
      "Tired is just weather. You move through it.",
      "Weariness is old. It doesn't own me.",
      "I march tired. I always have.",
    ],
    death: [
      "He fought for a place he couldn't go back to. That's the bravest thing.",
      "He carried his home in his chest. It's buried with him now.",
      "His country owes him a debt it can't pay. Remember his name.",
      "He lost his home and still found reasons to fight. What does that say about him.",
      "He was far from everything familiar and he never let that stop him.",
      "He belonged nowhere and showed up everywhere anyway. Honor that.",
      "He had no home left. He still showed up.",
      "Remember the place he came from. Say it once.",
    ],
  },
};

/** Exposed for tests — minimum 8 lines per archetype × moment (Wave 11). */
export const QUOTE_TABLE: Record<Archetype, QuoteTable> = QUOTES;

/**
 * Get a quote for an archetype at a specific moment.
 * Uses the RNG counter for deterministic selection.
 */
export function getArchetypeQuote(
  archetypeId: string,
  moment: QuoteMoment,
  seed: string,
  counter: number,
): string | null {
  const table = QUOTES[archetypeId as Archetype];
  if (!table) return null;
  const lines = table[moment];
  if (!lines || lines.length === 0) return null;
  // Simple deterministic pick
  const h = fnv1a(seed + counter);
  return lines[h % lines.length]!;
}

/** Pick quote moment from game state (mirrors UI pickOutcomeMoment). */
export function pickQuoteMomentForOutcome(
  game: Pick<GameState, "crew" | "rngCounter">,
  subT: PlaySub["t"] | string,
): QuoteMoment {
  if (subT === "briefing") return "start";
  const living = game.crew.filter((c) => c.hp > 0);
  const anyTired = living.some((c) => c.constitution < 40);
  if (anyTired && subT === "foot") return "tired";
  const anyCritical = living.some((c) => c.hp <= 2);
  if (anyCritical) return "down";
  return "win";
}

/** Pick who delivers an archetype quote (voice leader when cmd KIA or briefing/start). */
export function pickQuoteSpeaker(
  crew: CrewMember[],
  moment: QuoteMoment,
  counter: number,
): CrewMember | undefined {
  const living = crew.filter((c) => c.hp > 0);
  if (living.length === 0) return undefined;
  const leader = resolveVoiceLeader(crew);
  if (!leader) return undefined;
  if (moment === "start" || !commanderIsAlive(crew)) return leader;
  return living[counter % living.length];
}

/** Append one crew quote line to narrative log after an outcome. */
export function formatOutcomeQuoteLine(
  game: Pick<GameState, "crew" | "runSeed" | "rngCounter">,
  moment: QuoteMoment,
): string | null {
  const speaker = pickQuoteSpeaker(game.crew, moment, game.rngCounter);
  if (!speaker) return null;
  const quote = getArchetypeQuote(
    speaker.archetypeId,
    moment,
    game.runSeed,
    game.rngCounter + 999,
  );
  if (!quote) return null;
  return `${speaker.nickname}: "${quote}"`;
}

function fnv1a(s: string): number {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
