import type { RuntimeEvent } from "../engine/types";
import type { PoolKindBuckets } from "./poolKinds";
import { registerPoolKindsAndRebuildPool } from "./poolKinds";

/** Wave 18 — Solo Content III (§2.9 long-term pool targets). */
export const WAVE18_EVENTS: Record<string, RuntimeEvent> = {
  // ── Historical anchors (+2 → 20) ───────────────────────────────────────────
  anchor_ruhr_pocket: {
    id: "anchor_ruhr_pocket",
    kind: "historical_anchor",
    atmosphere: "Surrender columns clog the roads. Victory looks like traffic jams and men who stopped shooting.",
    narrative:
      "Ruhr pocket collapse — {objective} through a landscape of white flags and stunned faces.\n\nThe war is ending in front of you. The guns haven't all heard yet.",
    quote: '{cmd}: "Treat prisoners fair. The war ends on how we act now, not how we fought yesterday."',
    preChoiceNpc: {
      speaker: "Capt. Brennan",
      line: "You're cutting through a pocket that's already breaking. Some units fight on. Most don't. Don't get shot by someone who already lost.",
    },
    choices: [
      {
        id: "channel",
        label: "Channel prisoners off the road — commander.",
        role: "commander",
        dialogueLine: "We'll run a corridor. Prisoners left, combat traffic right. No mixing.",
        outcomeText: "Order imposed on chaos. Slow, but nobody runs down a man with his hands up.",
        effects: [
          { op: "mod_all_constitution", delta: 5 },
          { op: "journal", text: "Ruhr pocket — prisoners channeled clean.", kind: "moment" },
        ],
      },
      {
        id: "push_through",
        label: "Push through the column — driver.",
        role: "driver",
        dialogueLine: "We can't wait on paperwork. Through the gap and keep rolling.",
        outcomeText: "Horns, shouts, a rifle butt on the hull. You break through. The crew doesn't look back much.",
        effects: [
          { op: "mod_tank_health", delta: -5 },
          { op: "mod_constitution", role: "driver", delta: -4 },
          { op: "add_salvage", amount: 2 },
        ],
      },
      {
        id: "search",
        label: "Search stragglers for weapons — gunner.",
        role: "gunner",
        dialogueLine: "Every tenth man gets a pat-down. I don't trust a white flag I can't see both hands for.",
        outcomeText: "Two pistols, one grenade without a pin. Paranoia pays once.",
        effects: [
          { op: "mod_constitution", role: "gunner", delta: 3 },
          { op: "mod_resource", key: "smallArmsMags", delta: 1 },
        ],
      },
    ],
  },
  anchor_wesel_assault: {
    id: "anchor_wesel_assault",
    kind: "historical_anchor",
    atmosphere: "Rhine smoke. Engineers first. Armor second. Prayers optional.",
    narrative:
      "Wesel — {objective} across the last big water before the heartland.\n\nEngineers tape routes under fire. Your tank is proof that someone believed in the timetable.",
    quote: "{ldr}: \"If the bridge goes while we're on it, we swim in armor. Just so everyone knows.\"",
    preChoiceNpc: {
      speaker: "Col. Whitfield",
      line: "First treads on the far bank before dawn or we lose the artillery window. I don't care how wet you get.",
    },
    useDice: true,
    choices: [
      {
        id: "lead_crossing",
        label: "Lead the crossing — commander.",
        role: "commander",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        dialogueLine: "We lead. First across, first to draw fire, first to hold the far bank.",
        outcomeText: "Water, smoke, tracers. The far bank is mud and alive. You hold it.",
        effects: [
          { op: "mod_all_constitution", delta: 6 },
          { op: "mod_tank_health", delta: -12 },
          { op: "journal", text: "Wesel crossing — led the assault.", kind: "moment" },
        ],
      },
      {
        id: "engineer_cover",
        label: "Cover engineers — gunner.",
        role: "gunner",
        modifierBonus: 1,
        choiceRisk: "tactical",
        dialogueLine: "We suppress the far bank until the tape is down. Engineers live, we cross clean.",
        outcomeText: "HE walks the treeline. Engineers finish. The crossing costs less blood than it should have.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 3 }],
      },
      {
        id: "ferry_wait",
        label: "Wait for ferry priority — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        dialogueLine: "I'll hold the ramp until they wave us. No heroics on a wet deck.",
        outcomeText: "The ferry takes you. Slow. Dry enough. The column curses your patience and survives it.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 5 }],
      },
    ],
  },

  // ── Elite encounters (+2) ──────────────────────────────────────────────────
  elite_jagdpanther_hollow: {
    id: "elite_jagdpanther_hollow",
    kind: "elite_encounter",
    atmosphere: "A hunting blind made of eighty tons. The Jagdpanther does not hurry.",
    narrative:
      "Jagdpanther — hull-down in a sunken lane. Long 88. No turret to shoot off.\n\nYou find the angle or the angle finds you.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: -2, label: "Jagdpanther" },
    choices: [
      {
        id: "ap_flank",
        label: "AP flank shot — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Side plate. Clang. Maybe through. Maybe not.",
        effects: [{ op: "spend_ammo", ammo: "AP", amount: 2 }],
      },
      {
        id: "smoke_reposition",
        label: "Smoke and reposition — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "WP blooms. You live in grey until geometry improves.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "driver_angle",
        label: "Driver buys the angle — hull exposed.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Tracks scream. The shot window opens. The hull remembers.",
        effects: [{ op: "mod_tank_health", delta: -8 }, { op: "spend_ammo", ammo: "AP", amount: 1 }],
      },
    ],
  },
  elite_farm_strongpoint: {
    id: "elite_farm_strongpoint",
    kind: "elite_encounter",
    atmosphere: "Stone barn. Loop-holed walls. The farm fights harder than the field.",
    narrative:
      "Fortified farm — MG upstairs, AT in the cellar, {objective} beyond the yard.\n\nClear it or bypass and leave a throat behind you.",
    useDice: true,
    enemy: { idealAmmo: "HE", combatMod: -1, label: "Farm strongpoint" },
    choices: [
      {
        id: "he_room",
        label: "HE the upper floor — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Brackets collapse timber. Silence isn't peace yet.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 3 }],
      },
      {
        id: "infantry_clear",
        label: "Hull MG and infantry — asst driver.",
        role: "asst_driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Suppress, move, suppress. The yard costs time and mags.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -2 }],
      },
      {
        id: "bypass",
        label: "Bypass the farm — commander.",
        role: "commander",
        modifierBonus: -1,
        choiceRisk: "cautious",
        outcomeText: "You leave the throat open. Something fires at the column behind you.",
        effects: [{ op: "mod_all_constitution", delta: -3 }],
      },
    ],
  },

  // ── Social beats (+4 → 20) ─────────────────────────────────────────────────
  social_mail_missing: {
    id: "social_mail_missing",
    kind: "rest",
    atmosphere: "Mail call without your name on it. The war shrinks to an empty envelope.",
    narrative:
      "Mail call — names called, paper passed, laughter that isn't for you.\n\nThe loader checks twice. The letter isn't late. It's gone.",
    choices: [
      {
        id: "share",
        label: "Share someone else's letter aloud — loader.",
        role: "loader",
        outcomeText: "You read for a man who can't read fast. The words help both of you a little.",
        effects: [{ op: "mod_all_constitution", delta: 6 }, { op: "mod_constitution", role: "loader", delta: 4 }],
      },
      {
        id: "write",
        label: "Write one anyway — commander.",
        role: "commander",
        outcomeText: "Ink on paper. Maybe it arrives. Maybe it matters that you tried.",
        effects: [{ op: "mod_constitution", role: "commander", delta: 8 }],
      },
      {
        id: "walk",
        label: "Walk away from the circle — gunner.",
        role: "gunner",
        outcomeText: "Silence beats pretending. The night is long either way.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: -5 }],
      },
    ],
  },
  social_silent_replacement: {
    id: "social_silent_replacement",
    kind: "rest",
    atmosphere: "New face. Old seat. Nobody introduces the ghost he replaced.",
    narrative:
      "Replacement gunner — young, quiet, already learning which questions not to ask.\n\nThe crew watches him like a forecast.",
    choices: [
      {
        id: "welcome",
        label: "Commander makes the introduction proper.",
        role: "commander",
        outcomeText: "Names and roles. Boundaries. The kid nods like he understands more than he does.",
        effects: [{ op: "mod_all_constitution", delta: 5 }],
      },
      {
        id: "space",
        label: "Give him space — driver.",
        role: "driver",
        outcomeText: "No speeches. Work teaches faster. He learns the hatch by feel.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 4 }],
      },
      {
        id: "test",
        label: "Loader runs him through the rack drill.",
        role: "loader",
        outcomeText: "Metal clacks. Timing off, then closer. Sweat replaces small talk.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 3 }, { op: "mod_all_constitution", delta: 3 }],
      },
    ],
  },
  social_chaplain_last_visit: {
    id: "social_chaplain_last_visit",
    kind: "rest",
    atmosphere: "Chaplain before the push — coffee, scripture, and the look of a man who counts returns.",
    narrative:
      "Padre stops by before tomorrow's move. He doesn't promise survival. He offers presence.\n\nSome men want words. Some want quiet.",
    preChoiceNpc: {
      speaker: "Fr. O'Malley",
      line: "I won't tell you it's God's plan. I'll tell you you're not alone in the hull if you don't want to be.",
    },
    choices: [
      {
        id: "talk",
        label: "Talk — loader.",
        role: "loader",
        dialogueLine: "I need to say some things out loud, Father.",
        outcomeText: "Words spill. Not all of them pretty. The load feels lighter for an hour.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 10 }],
      },
      {
        id: "silence",
        label: "Sit in silence — commander.",
        role: "commander",
        dialogueLine: "Sit with us. No sermon.",
        outcomeText: "Quiet holds. Coffee cools. Nobody fills it wrong.",
        effects: [{ op: "mod_all_constitution", delta: 7 }],
      },
      {
        id: "outside",
        label: "Gunner stays outside — not today.",
        role: "gunner",
        outcomeText: "Cold air. Honest distance. The crew doesn't judge.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: -2 }],
      },
    ],
  },
  social_promotion_paperwork: {
    id: "social_promotion_paperwork",
    kind: "rest",
    atmosphere: "Stripes on paper. Rank on a collar. The war decides which one matters.",
    narrative:
      "Promotion paperwork — {cmd}'s name on a form, someone else's signature above it.\n\nStripes mean responsibility. The crew watches to see if you'll wear them different.",
    choices: [
      {
        id: "accept",
        label: "Accept with a speech — commander.",
        role: "commander",
        outcomeText: "Short words. Honest ones. The crew listens like it's orders.",
        effects: [{ op: "mod_all_constitution", delta: 8 }],
      },
      {
        id: "deflect",
        label: "Deflect to the crew — gunner.",
        role: "gunner",
        outcomeText: "Stripes on one collar. Work on five pairs of hands. Close enough.",
        effects: [{ op: "mod_all_constitution", delta: 5 }, { op: "mod_constitution", role: "gunner", delta: 4 }],
      },
      {
        id: "burn",
        label: "Dark humor — burn the copy.",
        role: "asst_driver",
        outcomeText: "Laughter. Paper ash. Rank stays on the collar anyway.",
        effects: [{ op: "mod_all_constitution", delta: 4 }, { op: "mod_constitution", role: "asst_driver", delta: 6 }],
      },
    ],
  },

  // ── Briefings (+2 → 8) ─────────────────────────────────────────────────────
  briefing_night_move: {
    id: "briefing_night_move",
    kind: "briefing",
    atmosphere: "Maps under red light. Night movement — every noise is a decision.",
    narrative:
      "Night march order — {objective} before dawn. Blackout drive, interval discipline, no headlights unless hell breaks loose.\n\n{tank} leads the second section.",
    quote: '{drv}: "Night driving is faith with treads. I need everyone quiet and everyone awake."',
    preChoiceNpc: {
      speaker: "Maj. Ellis",
      line: "You move at 0200. If you light up, you die. If you fall behind, you die slower.",
    },
    choices: [
      {
        id: "intervals",
        label: "\"Tight intervals — I'll keep the column closed.\"",
        role: "driver",
        dialogueLine: "I'll keep second section tight on the leader. No gaps.",
        outcomeText: "Ellis taps the map. Discipline before speed.",
        npcReply: "Tight is good. Don't tailgate the mine rollers.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 5 }, { op: "mod_all_constitution", delta: 3 }],
      },
      {
        id: "scout",
        label: "\"Request a scout vehicle ahead.\"",
        role: "commander",
        dialogueLine: "We need eyes beyond the lead tank. Request a scout section.",
        outcomeText: "Scout assigned. The road feels less like a trap — slightly.",
        npcReply: "Scout goes two hundred meters. You still own your own mistakes.",
        effects: [{ op: "mod_all_constitution", delta: 4 }, { op: "add_salvage", amount: 1 }],
      },
      {
        id: "ack",
        label: "\"Understood.\" [mount up]",
        role: "commander",
        dialogueLine: "Understood. Blackout at 0200.",
        flavorOnly: true,
        outcomeText: "Red light off. Engines cough. The night swallowing the column.",
        effects: [],
      },
    ],
  },
  briefing_ammo_hold: {
    id: "briefing_ammo_hold",
    kind: "briefing",
    atmosphere: "Ammo counts on the board. Hold orders on the map. Both say the same thing: spend carefully.",
    narrative:
      "Hold the line with what you have — {objective} until relief. Resupply is thin; HE is thinner.\n\n{tank} anchors the junction. Every round is a loan.",
    quote: "{gnr}: \"I can hit what I can see. I can't hit what we already spent.\"",
    preChoiceNpc: {
      speaker: "Lt. Carver",
      line: "You hold until 1800. No wasteful fires. If they probe, you answer. If they mass, you call arty and pray.",
    },
    choices: [
      {
        id: "discipline",
        label: "\"Ammo discipline — only confirmed targets.\"",
        role: "gunner",
        dialogueLine: "Confirmed targets only. No ranging shots on shadows.",
        outcomeText: "Carver nods. The gunner's jaw sets like a lock.",
        npcReply: "Good. I need that gun alive at 1801.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 6 }, { op: "mod_all_constitution", delta: 3 }],
      },
      {
        id: "fallback",
        label: "\"Fallback grid if they flank left.\"",
        role: "commander",
        dialogueLine: "If they flank left, we fall back to grid 442. I want it marked now.",
        outcomeText: "Grid marked. Escape routes are morale you can measure.",
        npcReply: "442 is good ground. Don't use it early.",
        effects: [{ op: "mod_all_constitution", delta: 5 }],
      },
      {
        id: "hold",
        label: "\"We hold.\" [mount up]",
        role: "commander",
        dialogueLine: "We hold the junction.",
        flavorOnly: true,
        outcomeText: "Simple order. Heavy math. The crew mounts.",
        effects: [],
      },
    ],
  },

  // ── Tier-1 procedural fillers (+15) ────────────────────────────────────────
  gen_travel_mud_supply: {
    id: "gen_travel_mud_supply",
    kind: "travel",
    atmosphere: "Supply trucks sunk to their axles. The road is a suggestion.",
    narrative:
      "Mud-choked supply point — rations stuck, fuel stuck, tempers not stuck enough.\n\nHelp them or pass and remember hunger later.",
    choices: [
      {
        id: "tow",
        label: "Tow the lead truck — driver.",
        role: "driver",
        outcomeText: "Tracks bite. Truck groans free. Gratitude and a case of rations.",
        effects: [{ op: "mod_tank_health", delta: -4 }, { op: "mod_resource", key: "foodDays", delta: 2 }],
      },
      {
        id: "pass",
        label: "Pass and report — commander.",
        role: "commander",
        outcomeText: "You radio the grid. Someone else solves it. Your schedule stays intact.",
        effects: [{ op: "mod_constitution", role: "commander", delta: -2 }],
      },
      {
        id: "hand_carry",
        label: "Hand-carry rations to the tank — loader.",
        role: "loader",
        outcomeText: "Mud to the knees. Food in the hull. Worth the stain.",
        effects: [{ op: "mod_resource", key: "foodDays", delta: 1 }, { op: "mod_constitution", role: "loader", delta: -3 }],
      },
    ],
  },
  gen_travel_wrong_grid: {
    id: "gen_travel_wrong_grid",
    kind: "travel",
    atmosphere: "Artillery falls where the map says friendly. Some clerk's mistake is your problem.",
    narrative:
      "Wrong-grid artillery — shells landing on a crossroads you need.\n\nStop, shout, pray the next round isn't yours.",
    useDice: true,
    choices: [
      {
        id: "radio",
        label: "Radio cease-fire — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Net chaos. Then silence. The crossroads steams.",
        effects: [{ op: "mod_constitution", role: "commander", delta: -4 }],
      },
      {
        id: "detour",
        label: "Detour east — driver.",
        role: "driver",
        modifierBonus: 0,
        choiceRisk: "cautious",
        outcomeText: "Long way. Quiet way. Fuel pays the toll.",
        effects: [{ op: "mod_resource", key: "foodDays", delta: -1 }],
      },
      {
        id: "run",
        label: "Run the bracket — driver.",
        role: "driver",
        modifierBonus: -1,
        choiceRisk: "aggressive",
        outcomeText: "Shells chase. Tracks don't slip. Luck does.",
        effects: [{ op: "mod_tank_health", delta: -8 }, { op: "mod_constitution", role: "driver", delta: 5 }],
      },
    ],
  },
  gen_travel_convoy_halt: {
    id: "gen_travel_convoy_halt",
    kind: "travel",
    atmosphere: "Engines idling. Nobody knows why. Rumors travel faster than orders.",
    narrative:
      "Convoy halt — column frozen, radios busy, patience thinning.\n\nWait for word or scout ahead on your own hook.",
    choices: [
      {
        id: "wait",
        label: "Hold position — commander.",
        role: "commander",
        outcomeText: "Order restored. Time lost. Nerves frayed evenly.",
        effects: [{ op: "mod_all_constitution", delta: -3 }],
      },
      {
        id: "scout",
        label: "Scout on foot — asst driver.",
        role: "asst_driver",
        outcomeText: "Bridge out two klicks. Now you know. Now you wait anyway.",
        effects: [{ op: "mod_constitution", role: "asst_driver", delta: 4 }, { op: "add_salvage", amount: 1 }],
      },
      {
        id: "maint",
        label: "Run maintenance while halted — loader.",
        role: "loader",
        outcomeText: "Rack cleared. Links checked. Useful hands beat useless fear.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 5 }],
      },
    ],
  },
  gen_supply_artillery_splash: {
    id: "gen_supply_artillery_splash",
    kind: "supply",
    atmosphere: "Supply dump smoking. Shells find piles before they find tanks.",
    narrative:
      "Artillery splash on a supply dump — ammo cooking off, men running, choices immediate.\n\nSalvage or leave before the next bracket.",
    choices: [
      {
        id: "grab",
        label: "Grab what you can — loader.",
        role: "loader",
        outcomeText: "Crates in the hull. Shrapnel in the paint. Fair trade.",
        effects: [
          { op: "add_salvage", amount: 2 },
          { op: "mod_tank_health", delta: -5 },
        ],
      },
      {
        id: "help",
        label: "Help wounded — loader as medic.",
        role: "loader",
        outcomeText: "Hands busy on blood instead of brass. Medkit spent. Humanity kept.",
        effects: [{ op: "mod_resource", key: "medkits", delta: -1 }, { op: "mod_all_constitution", delta: 6 }],
      },
      {
        id: "leave",
        label: "Leave — commander.",
        role: "commander",
        outcomeText: "The dump burns behind you. The column still needs you intact.",
        effects: [{ op: "mod_constitution", role: "commander", delta: 3 }],
      },
    ],
  },
  gen_supply_water_shortage: {
    id: "gen_supply_water_shortage",
    kind: "supply",
    atmosphere: "Water cans low. Heat or march — either way, throats win arguments.",
    narrative:
      "Water shortage — division ration cut again.\n\nShare, steal, or suffer.",
    choices: [
      {
        id: "share",
        label: "Share evenly — commander.",
        role: "commander",
        outcomeText: "Nobody happy. Nobody dead of thirst today.",
        effects: [{ op: "mod_resource", key: "waterCanteens", delta: -1 }, { op: "mod_all_constitution", delta: 2 }],
      },
      {
        id: "find",
        label: "Find a well — driver.",
        role: "driver",
        outcomeText: "Farm well. Chlorine tabs. Ugly taste. Beautiful math.",
        effects: [{ op: "mod_resource", key: "waterCanteens", delta: 2 }, { op: "mod_tank_health", delta: -3 }],
      },
      {
        id: "priority",
        label: "Crew first, engine second — loader.",
        role: "loader",
        outcomeText: "Men drink. Radiator waits. Moral arithmetic.",
        effects: [{ op: "mod_all_constitution", delta: 5 }, { op: "mod_resource", key: "waterCanteens", delta: -2 }],
      },
    ],
  },
  gen_human_cellar_family: {
    id: "gen_human_cellar_family",
    kind: "human_moment",
    atmosphere: "Cellar door open. Eyes in the dark. War upstairs, fear downstairs.",
    narrative:
      "Civilian cellar — family, bread smell, a child who won't stop staring at your gun.\n\nHelp, move on, or call MP.",
    choices: [
      {
        id: "rations",
        label: "Leave rations — loader.",
        role: "loader",
        outcomeText: "Food on the step. No speeches. The door closes gentle.",
        effects: [{ op: "mod_resource", key: "foodDays", delta: -1 }, { op: "mod_all_constitution", delta: 5 }],
      },
      {
        id: "move",
        label: "Move on — commander.",
        role: "commander",
        outcomeText: "Not your fight. Not your fault. The image stays anyway.",
        effects: [{ op: "mod_constitution", role: "commander", delta: -3 }],
      },
      {
        id: "mp",
        label: "Mark for MP — asst driver.",
        role: "asst_driver",
        outcomeText: "Grid noted. Procedure followed. Humanity filed away.",
        effects: [{ op: "add_salvage", amount: 1 }],
      },
    ],
  },
  gen_human_wrong_unit: {
    id: "gen_human_wrong_unit",
    kind: "human_moment",
    atmosphere: "Wrong patch on the right road. Confusion kills faster than malice.",
    narrative:
      "Wrong unit on the road — uniforms similar, accents not, everyone twitchy.\n\nChallenge or pass and hope.",
    choices: [
      {
        id: "challenge",
        label: "Challenge passwords — commander.",
        role: "commander",
        outcomeText: "Words exchanged. Tension drops. Nobody fires.",
        effects: [{ op: "mod_all_constitution", delta: 4 }],
      },
      {
        id: "cover",
        label: "Gunner covers while commander talks.",
        role: "gunner",
        outcomeText: "Muzzle steady. Voices calm. The moment passes.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 3 }],
      },
      {
        id: "pass",
        label: "Pass wide — driver.",
        role: "driver",
        outcomeText: "Distance is diplomacy. You take the ditch.",
        effects: [{ op: "mod_tank_health", delta: -3 }],
      },
    ],
  },
  npc_radioman_net: {
    id: "npc_radioman_net",
    kind: "npc_conversation",
    atmosphere: "Static on every frequency. Someone else's net is screaming for help.",
    narrative:
      "Division radioman — headset crooked, pencil broken, net compromised.\n\nShare codes, stay silent, or switch frequency.",
    preChoiceNpc: {
      speaker: "Sig. Corporal Hale",
      line: "Net's dirty. I need a tank crew who won't broadcast our grid to every listener.",
    },
    choices: [
      {
        id: "help",
        label: "Help relay — commander.",
        role: "commander",
        dialogueLine: "Give us the traffic. We'll relay clean on the armored net.",
        outcomeText: "Messages pass. Grid stays quiet. Hale buys you coffee later.",
        effects: [{ op: "add_salvage", amount: 2 }, { op: "mod_all_constitution", delta: 3 }],
      },
      {
        id: "ignore",
        label: "Stay off the net — driver.",
        role: "driver",
        dialogueLine: "We stay dark. You handle your mess.",
        outcomeText: "Silence kept. Ignorance chosen. Safer maybe.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 4 }],
      },
      {
        id: "flavor",
        label: "Ask about the front — loader.",
        role: "loader",
        flavorOnly: true,
        dialogueLine: "What's actually happening out there?",
        outcomeText: "Hale talks too fast. You understand enough to wish you didn't.",
        effects: [],
      },
    ],
  },
  npc_surrender_column: {
    id: "npc_surrender_column",
    kind: "npc_conversation",
    atmosphere: "Men walking toward captivity. The war leaves the body before the mind.",
    narrative:
      "Surrender column crossing your path — exhausted, orderly, unreal.\n\nEscort, pass, or search.",
    preChoiceNpc: {
      speaker: "German NCO (English)",
      line: "We march to your lines. No fight left. Please — no accidents.",
    },
    choices: [
      {
        id: "escort",
        label: "Escort to MP point — commander.",
        role: "commander",
        dialogueLine: "Fall in behind us. MP grid in two kilometers.",
        outcomeText: "Column merges. Slow march. War thinning.",
        effects: [{ op: "mod_all_constitution", delta: 4 }, { op: "journal", text: "Escorted surrender column.", kind: "moment" }],
      },
      {
        id: "pass",
        label: "Pass left — driver.",
        role: "driver",
        dialogueLine: "Clear the road. We pass left.",
        outcomeText: "Space made. Eyes down. Tracks roll.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 2 }],
      },
      {
        id: "search",
        label: "Quick weapons search — gunner.",
        role: "gunner",
        dialogueLine: "Hands visible. We search the first rank.",
        outcomeText: "Blades, one pistol. Removed. March continues.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 3 }],
      },
    ],
  },
  gen_combat_pz4_ambush: {
    id: "gen_combat_pz4_ambush",
    kind: "tank_combat",
    atmosphere: "Panzer IV — old design, good crew, bad timing for you.",
    narrative: "Panzer IV ambush from a barn slit. Close range. Fast choices.\n\nAP, HE, or smoke.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: 0, label: "Panzer IV" },
    choices: [
      {
        id: "ap",
        label: "AP center mass — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Two guns speak. One stops.",
        effects: [{ op: "spend_ammo", ammo: "AP", amount: 2 }],
      },
      {
        id: "he",
        label: "HE the barn — gunner.",
        role: "gunner",
        modifierBonus: -1,
        choiceRisk: "tactical",
        outcomeText: "Timber and fire. Tank maybe dead. Barn definitely dead.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
      {
        id: "smoke",
        label: "Smoke and reverse — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Grey out. Tracks back. Geometry reset.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
    ],
  },
  gen_combat_flak88_roadblock: {
    id: "gen_combat_flak88_roadblock",
    kind: "tank_combat",
    atmosphere: "Eighty-eight as roadblock. The gun that learned every role.",
    narrative: "Flak 88 on the road — depressed muzzle, confident crew.\n\nSuppress, flank, or eat the first round.",
    useDice: true,
    enemy: { idealAmmo: "HE", combatMod: -1, label: "Flak 88" },
    choices: [
      {
        id: "he",
        label: "HE suppress — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Dirt geysers. Gun silent maybe.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
      {
        id: "flank",
        label: "Flank through the field — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Angle gained. Hull exposed. Shot taken.",
        effects: [{ op: "mod_tank_health", delta: -6 }, { op: "spend_ammo", ammo: "AP", amount: 1 }],
      },
      {
        id: "smoke",
        label: "Smoke screen — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "WP wall. Move under cover.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
    ],
  },
  gen_infantry_artillery_mist: {
    id: "gen_infantry_artillery_mist",
    kind: "infantry_combat",
    atmosphere: "Friendly arty falling short. Infantry pinned. Radios hot.",
    narrative: "Artillery mistake on your own infantry — shells short, men screaming on the net.\n\nStop the fire, move, or pray.",
    useDice: true,
    choices: [
      {
        id: "radio",
        label: "Radio cease-fire — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Net flares. Fire lifts. Bodies still.",
        effects: [{ op: "mod_all_constitution", delta: -4 }],
      },
      {
        id: "smoke",
        label: "Smoke the grid — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "cautious",
        outcomeText: "WP marks the line. Adjust fire. Breathing resumes.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "extract",
        label: "Extract wounded — loader.",
        role: "loader",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Medkit out. Men dragged. Shells still fall somewhere.",
        effects: [{ op: "mod_resource", key: "medkits", delta: -1 }, { op: "mod_all_constitution", delta: 5 }],
      },
    ],
  },
  gen_infantry_surrender_wave: {
    id: "gen_infantry_surrender_wave",
    kind: "infantry_combat",
    atmosphere: "Hands up. Weapons down. The fight leaves faster than courage returns.",
    narrative: "Surrender wave — infantry rising from holes, calling in broken English.\n\nHold fire, search, or call MP.",
    useDice: true,
    choices: [
      {
        id: "hold",
        label: "Hold fire — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Triggers quiet. Men live who expected not to.",
        effects: [{ op: "mod_all_constitution", delta: 6 }],
      },
      {
        id: "search",
        label: "Search before trust — asst driver.",
        role: "asst_driver",
        modifierBonus: 0,
        choiceRisk: "tactical",
        outcomeText: "Knives out. One grenade tossed. Rest march.",
        effects: [{ op: "mod_constitution", role: "asst_driver", delta: 3 }],
      },
      {
        id: "cover",
        label: "Cover the approach — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Muzzle down but ready. Discipline holds.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 4 }],
      },
    ],
  },
  gen_defensive_ruhr_line: {
    id: "gen_defensive_ruhr_line",
    kind: "defensive_stand",
    atmosphere: "Last coherent line. Everything after is improvisation.",
    narrative: "Ruhr defensive line — probes at dusk, maybe a push at dawn.\n\nHold, spoiling attack, or bend.",
    useDice: true,
    choices: [
      {
        id: "hold",
        label: "Hold the junction — commander.",
        role: "commander",
        modifierBonus: 0,
        choiceRisk: "cautious",
        outcomeText: "Night passes. Ground stays. Nerves don't.",
        effects: [{ op: "mod_all_constitution", delta: -5 }],
      },
      {
        id: "spoiling",
        label: "Spoiling HE — gunner.",
        role: "gunner",
        modifierBonus: 1,
        choiceRisk: "aggressive",
        outcomeText: "HE walks the tree line. Probes stop. Ammo lighter.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
      {
        id: "fallback",
        label: "Fighting fallback — driver.",
        role: "driver",
        modifierBonus: 0,
        choiceRisk: "tactical",
        outcomeText: "Bound back grid by grid. Orderly. Costly.",
        effects: [{ op: "mod_tank_health", delta: -5 }],
      },
    ],
  },
  gen_offensive_bypass_town: {
    id: "gen_offensive_bypass_town",
    kind: "offensive_assault",
    atmosphere: "Town on the map. Town in the way. Command wants speed.",
    narrative: "Bypass order — skirt the town, cut the road behind, leave the garrison guessing.\n\nFast, loud, or careful.",
    useDice: true,
    choices: [
      {
        id: "speed",
        label: "Full speed bypass — driver.",
        role: "driver",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Tracks hammer mud. AT misses. You don't.",
        effects: [{ op: "mod_tank_health", delta: -6 }, { op: "add_salvage", amount: 2 }],
      },
      {
        id: "smoke",
        label: "Smoke the town — gunner.",
        role: "gunner",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "WP on the rooftops. Bypass under cover.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "hold_road",
        label: "Cut the road and hold — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Road blocked. Garrison isolated. Time bought.",
        effects: [{ op: "mod_all_constitution", delta: 4 }],
      },
    ],
  },
};

export const WAVE18_TIER1_IDS = [
  "gen_travel_mud_supply",
  "gen_travel_wrong_grid",
  "gen_travel_convoy_halt",
  "gen_supply_artillery_splash",
  "gen_supply_water_shortage",
  "gen_human_cellar_family",
  "gen_human_wrong_unit",
  "npc_radioman_net",
  "npc_surrender_column",
  "gen_combat_pz4_ambush",
  "gen_combat_flak88_roadblock",
  "gen_infantry_artillery_mist",
  "gen_infantry_surrender_wave",
  "gen_defensive_ruhr_line",
  "gen_offensive_bypass_town",
] as const;

export const WAVE18_ANCHOR_IDS = ["anchor_ruhr_pocket", "anchor_wesel_assault"] as const;

export const WAVE18_SOCIAL_IDS = [
  "social_mail_missing",
  "social_silent_replacement",
  "social_chaplain_last_visit",
  "social_promotion_paperwork",
] as const;

export const WAVE18_BRIEFING_IDS = ["briefing_night_move", "briefing_ammo_hold"] as const;

export const WAVE18_POOL_KIND_BUCKETS: Partial<PoolKindBuckets> = {
  travel: ["gen_travel_mud_supply", "gen_travel_wrong_grid", "gen_travel_convoy_halt"],
  supply: ["gen_supply_artillery_splash", "gen_supply_water_shortage"],
  human: ["gen_human_cellar_family", "gen_human_wrong_unit"],
  npc: ["npc_radioman_net", "npc_surrender_column"],
  combat: ["gen_combat_pz4_ambush", "gen_combat_flak88_roadblock"],
  infantry: ["gen_infantry_artillery_mist", "gen_infantry_surrender_wave"],
  defensive: ["gen_defensive_ruhr_line"],
  offensive: ["gen_offensive_bypass_town"],
  elite: ["elite_jagdpanther_hollow", "elite_farm_strongpoint"],
};

export function applyWave18PoolRegistration(): string[] {
  return registerPoolKindsAndRebuildPool(WAVE18_POOL_KIND_BUCKETS);
}
