import type { RuntimeEvent } from "../engine/types";
import type { PoolKindBuckets } from "./poolKinds";
import { registerTier2PoolKinds } from "./poolKinds";

/** Wave 16 — Tier-2 procedural fillers (§2.9). Disjoint from GENERIC_POOL. */
export const WAVE16_EVENTS: Record<string, RuntimeEvent> = {
  gen2_travel_orchard_lane: {
    id: "gen2_travel_orchard_lane",
    kind: "travel",
    atmosphere: "Apple wood and diesel. The lane is too narrow for comfort.",
    narrative: "Orchard lane — branches scrape the hull. {objective} waits past the last row of trees.\n\nOne wrong turn and the column stops.",
    choices: [
      {
        id: "push",
        label: "Push through — driver.",
        role: "driver",
        outcomeText: "Branches snap. Paint scraped. Road open.",
        effects: [{ op: "mod_tank_health", delta: -4 }, { op: "mod_constitution", role: "driver", delta: 3 }],
      },
      {
        id: "trim",
        label: "Trim with wire — loader.",
        role: "loader",
        outcomeText: "Wire and patience. Slower. Cleaner.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -1 }, { op: "mod_all_constitution", delta: 2 }],
      },
      {
        id: "detour",
        label: "Detour south — commander.",
        role: "commander",
        outcomeText: "Long way. Quiet way.",
        effects: [{ op: "mod_resource", key: "foodDays", delta: -1 }, { op: "mod_all_constitution", delta: 4 }],
      },
    ],
  },
  gen2_travel_sunken_road: {
    id: "gen2_travel_sunken_road",
    kind: "travel",
    atmosphere: "Walls of mud on both sides. Sky is a ribbon.",
    narrative: "Sunken road — perfect ambush geometry. {tank} crawls with hatches cracked.\n\nEvery window is a threat.",
    choices: [
      {
        id: "speed",
        label: "Speed through — driver.",
        role: "driver",
        outcomeText: "Fast. Exposed. Through.",
        effects: [{ op: "mod_constitution", role: "driver", delta: -3 }, { op: "mod_all_constitution", delta: 2 }],
      },
      {
        id: "infantry",
        label: "Infantry ahead — asst driver.",
        role: "asst_driver",
        outcomeText: "Boots on the rim. Eyes on the windows.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -1 }, { op: "mod_constitution", role: "asst_driver", delta: 4 }],
      },
      {
        id: "smoke",
        label: "Smoke the length — gunner.",
        role: "gunner",
        outcomeText: "Grey tunnel. Nobody shoots what they cannot see.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
    ],
  },
  gen2_travel_pontoon_queue: {
    id: "gen2_travel_pontoon_queue",
    kind: "travel",
    atmosphere: "Engines idling. Engineers swear at the current.",
    narrative: "Pontoon queue — half the battalion waits on the bank. {objective} is the other side.\n\nTime is a resource you are spending.",
    choices: [
      {
        id: "priority",
        label: "Demand priority — commander.",
        role: "commander",
        outcomeText: "Paper wins. You cross sooner. Friends remember.",
        effects: [{ op: "mod_all_constitution", delta: -2 }, { op: "mod_constitution", role: "commander", delta: 5 }],
      },
      {
        id: "wait",
        label: "Wait your turn — driver.",
        role: "driver",
        outcomeText: "Hours. Nerves. No drama.",
        effects: [{ op: "mod_all_constitution", delta: 3 }],
      },
      {
        id: "help",
        label: "Help lash pontoons — loader.",
        role: "loader",
        outcomeText: "Muscle for goodwill. Cross in the second wave.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 6 }, { op: "mod_resource", key: "waterCanteens", delta: -1 }],
      },
    ],
  },
  gen2_travel_signal_cabin: {
    id: "gen2_travel_signal_cabin",
    kind: "travel",
    atmosphere: "A signal cabin with a dead phone and a living map.",
    narrative: "Rail signal cabin — maps pinned to sooty walls. Route for {objective} might be wrong.\n\nTrust the paper or trust the road.",
    choices: [
      {
        id: "map",
        label: "Copy the map — commander.",
        role: "commander",
        outcomeText: "Intel saved. Time lost.",
        effects: [{ op: "seed_flag", flag: "gen2_map_copied" }, { op: "mod_all_constitution", delta: 3 }],
      },
      {
        id: "scout",
        label: "Scout the spur — asst driver.",
        role: "asst_driver",
        outcomeText: "Spur is clear. Shortcut taken.",
        effects: [{ op: "mod_constitution", role: "asst_driver", delta: 4 }],
      },
      {
        id: "ignore",
        label: "Stay on main trace — driver.",
        role: "driver",
        outcomeText: "Main road. Slow. Predictable.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 2 }],
      },
    ],
  },
  gen2_travel_cattle_on_road: {
    id: "gen2_travel_cattle_on_road",
    kind: "travel",
    atmosphere: "Cattle block the trace. Farmers watch from a ditch.",
    narrative: "Herd on the road — {tank} cannot push without making enemies of civilians.\n\n{objective} does not care about your diplomacy.",
    choices: [
      {
        id: "horn",
        label: "Horn and inch forward — driver.",
        role: "driver",
        outcomeText: "Animals scatter. Tempers flare.",
        effects: [{ op: "mod_all_constitution", delta: -2 }],
      },
      {
        id: "herd",
        label: "Help herd them off — loader.",
        role: "loader",
        outcomeText: "Sweat and goodwill. Road clears.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 5 }, { op: "mod_resource", key: "foodDays", delta: -1 }],
      },
      {
        id: "bypass",
        label: "Bypass through the field — commander.",
        role: "commander",
        outcomeText: "Tracks sink. Column moves.",
        effects: [{ op: "set_component", component: "track_right", status: "damaged" }, { op: "mod_tank_health", delta: -3 }],
      },
    ],
  },
  gen2_travel_demolished_church: {
    id: "gen2_travel_demolished_church",
    kind: "travel",
    atmosphere: "Bell tower rubble. Stained glass in the mud.",
    narrative: "Demolished church — good overwatch, bad optics. Route to {objective} cuts through the nave.\n\nSacred ground, tactical ground.",
    choices: [
      {
        id: "through",
        label: "Drive through the rubble — driver.",
        role: "driver",
        outcomeText: "Stone grinds treads. You are through.",
        effects: [{ op: "mod_tank_health", delta: -5 }, { op: "mod_constitution", role: "driver", delta: 2 }],
      },
      {
        id: "around",
        label: "Go around the cemetery — commander.",
        role: "commander",
        outcomeText: "Respect costs distance. Distance costs time.",
        effects: [{ op: "mod_all_constitution", delta: 4 }],
      },
      {
        id: "watch",
        label: "Gunner overwatch while column passes — gunner.",
        role: "gunner",
        outcomeText: "Silent tower. No shots.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 3 }],
      },
    ],
  },
  gen2_travel_forest_gap: {
    id: "gen2_travel_forest_gap",
    kind: "travel",
    atmosphere: "Sun through canopy. Tank width minus two inches.",
    narrative: "Forest gap — tight timber. {tank} is the widest thing here.\n\nBranches sound like rifle cracks.",
    choices: [
      {
        id: "inch",
        label: "Inch by inch — driver.",
        role: "driver",
        outcomeText: "Paint gone. Nerves intact.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 5 }],
      },
      {
        id: "dismount",
        label: "Dismount and guide — asst driver.",
        role: "asst_driver",
        outcomeText: "Hand signals. No scratches.",
        effects: [{ op: "mod_constitution", role: "asst_driver", delta: 6 }, { op: "mod_resource", key: "foodDays", delta: -1 }],
      },
      {
        id: "clear",
        label: "Clear with HE — gunner.",
        role: "gunner",
        outcomeText: "Timber down. Noise up. Gap open.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 1 }, { op: "mod_all_constitution", delta: -3 }],
      },
    ],
  },
  gen2_supply_river_ford: {
    id: "gen2_supply_river_ford",
    kind: "supply",
    atmosphere: "Cold water at the hubs. The ford is half silt, half nerve.",
    narrative: "River ford — engineers marked it shallow. {objective} is beyond the far bank.\n\nWet tracks freeze. Wet crews freeze faster.",
    choices: [
      {
        id: "ford",
        label: "Ford now — driver.",
        role: "driver",
        outcomeText: "Water to the sponsons. You climb out the far side.",
        effects: [{ op: "mod_tank_health", delta: -4 }, { op: "mod_constitution", role: "driver", delta: 4 }],
      },
      {
        id: "probe",
        label: "Probe depth on foot — loader.",
        role: "loader",
        outcomeText: "Depth known. Crossing safer.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 3 }, { op: "mod_resource", key: "waterCanteens", delta: -1 }],
      },
      {
        id: "wait",
        label: "Wait for engineer tape — commander.",
        role: "commander",
        outcomeText: "Tape arrives. Crossing boring and alive.",
        effects: [{ op: "mod_all_constitution", delta: 5 }],
      },
    ],
  },
  gen2_supply_wire_roll: {
    id: "gen2_supply_wire_roll",
    kind: "supply",
    atmosphere: "Concertina gleams like a cruel necklace.",
    narrative: "Wire roll found on a abandoned truck. Could brace a night position for {objective}.\n\nWeight you do not need versus sleep you do.",
    choices: [
      {
        id: "take",
        label: "Take the wire — loader.",
        role: "loader",
        outcomeText: "Wire aboard. Night defense improved.",
        effects: [{ op: "add_salvage", amount: 1 }, { op: "mod_constitution", role: "loader", delta: 3 }],
      },
      {
        id: "leave",
        label: "Leave it — commander.",
        role: "commander",
        outcomeText: "Lighter. Faster. Softer at night.",
        effects: [{ op: "mod_all_constitution", delta: 2 }],
      },
      {
        id: "trade",
        label: "Trade wire for rations — gunner.",
        role: "gunner",
        outcomeText: "Swap done. Bellies warmer.",
        effects: [{ op: "mod_resource", key: "foodDays", delta: 2 }, { op: "mod_resource", key: "smallArmsMags", delta: -1 }],
      },
    ],
  },
  gen2_supply_oil_drum: {
    id: "gen2_supply_oil_drum",
    kind: "supply",
    atmosphere: "Black drum. Smell of fuel and trouble.",
    narrative: "Captured fuel drum — maybe German, maybe American mislabeled.\n\n{objective} needs miles. Engines need trust.",
    choices: [
      {
        id: "use",
        label: "Top off the tanks — driver.",
        role: "driver",
        outcomeText: "Engine purrs. You hope it is not water.",
        effects: [{ op: "mod_tank_health", delta: 3 }, { op: "mod_constitution", role: "driver", delta: -2 }],
      },
      {
        id: "test",
        label: "Test burn on a rag — loader.",
        role: "loader",
        outcomeText: "Clean flame. Good fuel.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 4 }],
      },
      {
        id: "mark",
        label: "Mark for ordnance — commander.",
        role: "commander",
        outcomeText: "EOD takes it. You move on.",
        effects: [{ op: "mod_all_constitution", delta: 3 }],
      },
    ],
  },
  gen2_supply_field_phone: {
    id: "gen2_supply_field_phone",
    kind: "supply",
    atmosphere: "Crank phone on a splintered post. Line still hums.",
    narrative: "Field phone at a crossroads — someone might still answer. {objective} might get clearer.\n\nEvery ring is a beacon.",
    choices: [
      {
        id: "call",
        label: "Crank for battalion — commander.",
        role: "commander",
        outcomeText: "Orders updated. Position known to everyone.",
        effects: [{ op: "mod_all_constitution", delta: 4 }, { op: "seed_flag", flag: "gen2_phone_called" }],
      },
      {
        id: "cut",
        label: "Cut the wire — gunner.",
        role: "gunner",
        outcomeText: "Silence. Isolation. Safety.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 3 }],
      },
      {
        id: "pass",
        label: "Pass without touching — driver.",
        role: "driver",
        outcomeText: "No signal. No trap.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 2 }],
      },
    ],
  },
  gen2_supply_grave_markers: {
    id: "gen2_supply_grave_markers",
    kind: "supply",
    atmosphere: "Wooden crosses in a row. Someone else's handwriting.",
    narrative: "Grave markers stacked by a ditch — lumber for a bridge or respect for the dead.\n\n{objective} will not wait for philosophy.",
    choices: [
      {
        id: "respect",
        label: "Leave them — commander.",
        role: "commander",
        outcomeText: "Crosses stay. Crew quieter.",
        effects: [{ op: "mod_all_constitution", delta: 6 }],
      },
      {
        id: "bridge",
        label: "Use for corduroy — driver.",
        role: "driver",
        outcomeText: "Road improved. Conscience heavy.",
        effects: [{ op: "mod_all_constitution", delta: -4 }, { op: "mod_tank_health", delta: 2 }],
      },
      {
        id: "bury",
        label: "Bury them proper — loader.",
        role: "loader",
        outcomeText: "Hours lost. Right thing done.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 8 }, { op: "mod_resource", key: "foodDays", delta: -1 }],
      },
    ],
  },
  gen2_human_trench_mirror: {
    id: "gen2_human_trench_mirror",
    kind: "human_moment",
    atmosphere: "A shaving mirror nailed to a post. Your face looks borrowed.",
    narrative: "Abandoned trench — mirror still hanging. Men check themselves before the next push toward {objective}.\n\nVanity or ritual.",
    choices: [
      {
        id: "look",
        label: "Look once — gunner.",
        role: "gunner",
        outcomeText: "Same eyes. Different war.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 4 }],
      },
      {
        id: "smash",
        label: "Smash it — loader.",
        role: "loader",
        outcomeText: "Glass gone. Superstition fed.",
        effects: [{ op: "mod_constitution", role: "loader", delta: -2 }, { op: "mod_all_constitution", delta: 2 }],
      },
      {
        id: "leave",
        label: "Leave it for the next man — commander.",
        role: "commander",
        outcomeText: "Mirror stays. You move.",
        effects: [{ op: "mod_all_constitution", delta: 3 }],
      },
    ],
  },
  gen2_human_bootlaces: {
    id: "gen2_human_bootlaces",
    kind: "human_moment",
    atmosphere: "A boot without a foot. Laces still tied.",
    narrative: "Bootlaces in the mud — someone ran without finishing dressing.\n\n{objective} does not pause for ghosts.",
    choices: [
      {
        id: "pocket",
        label: "Pocket the laces — loader.",
        role: "loader",
        outcomeText: "Luck charm. Ugly luck.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 5 }],
      },
      {
        id: "bury",
        label: "Bury the boot — asst driver.",
        role: "asst_driver",
        outcomeText: "Small grave. Small peace.",
        effects: [{ op: "mod_constitution", role: "asst_driver", delta: 6 }],
      },
      {
        id: "march",
        label: "March on — commander.",
        role: "commander",
        outcomeText: "Road takes the dead. You take the living.",
        effects: [{ op: "mod_all_constitution", delta: -2 }],
      },
    ],
  },
  gen2_human_prayer_card: {
    id: "gen2_human_prayer_card",
    kind: "human_moment",
    atmosphere: "Laminated prayer card. Ink smeared by rain.",
    narrative: "Prayer card in the cupola — German saint, universal fear.\n\nSomeone prayed before {objective}.",
    choices: [
      {
        id: "keep",
        label: "Keep it — gunner.",
        role: "gunner",
        outcomeText: "Card in pocket. Weightless armor.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 5 }],
      },
      {
        id: "return",
        label: "Leave on the hatch — commander.",
        role: "commander",
        outcomeText: "Gesture without words.",
        effects: [{ op: "mod_all_constitution", delta: 4 }],
      },
      {
        id: "burn",
        label: "Burn it — loader.",
        role: "loader",
        outcomeText: "Ash in the wind. Mood harder.",
        effects: [{ op: "mod_all_constitution", delta: -3 }],
      },
    ],
  },
  gen2_human_map_pin: {
    id: "gen2_human_map_pin",
    kind: "human_moment",
    atmosphere: "Map pin through a photograph. Smile hole-punched.",
    narrative: "Map with a pin through a woman's face — some clerk's cruel shorthand.\n\n{objective} sits on the same grid.",
    choices: [
      {
        id: "pull",
        label: "Pull the pin — commander.",
        role: "commander",
        outcomeText: "Face whole again. Order feels less obscene.",
        effects: [{ op: "mod_all_constitution", delta: 5 }],
      },
      {
        id: "note",
        label: "Note the grid — gunner.",
        role: "gunner",
        outcomeText: "Grid memorized. Person forgotten.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 2 }],
      },
      {
        id: "discard",
        label: "Discard the map — driver.",
        role: "driver",
        outcomeText: "New map. Old guilt stays.",
        effects: [{ op: "mod_constitution", role: "driver", delta: -2 }],
      },
    ],
  },
  gen2_npc_regimental_band: {
    id: "gen2_npc_regimental_band",
    kind: "npc_conversation",
    atmosphere: "Brass and dust. Music where shells should be.",
    narrative: "Regimental band in a barn — playing for nobody, waiting for {objective} to matter.\n\nBeauty feels indecent.",
    preChoiceNpc: { speaker: "Bandmaster Ellis", line: "We play so men remember they are men. You want a tune or silence?" },
    choices: [
      {
        id: "tune",
        label: "\"Play something slow.\"",
        role: "commander",
        dialogueLine: "Something slow. No parade.",
        npcReply: "Slow it is. Try not to cry where the men can see.",
        outcomeText: "Music fills the barn. Nerves unknot.",
        effects: [{ op: "mod_all_constitution", delta: 8 }],
      },
      {
        id: "silence",
        label: "\"Silence is fine.\"",
        role: "gunner",
        dialogueLine: "We have enough noise.",
        npcReply: "Fair. Good luck out there.",
        outcomeText: "Quiet march. Honest quiet.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 3 }],
      },
      {
        id: "march",
        label: "\"Save it for the parade.\"",
        role: "loader",
        dialogueLine: "Save the breath.",
        npcReply: "Parade's a fantasy. We play anyway.",
        outcomeText: "You leave. Music follows in your head.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 2 }],
      },
    ],
  },
  gen2_npc_quartermaster_grump: {
    id: "gen2_npc_quartermaster_grump",
    kind: "npc_conversation",
    atmosphere: "Clipboard, cigar, zero sympathy.",
    narrative: "Quartermaster tent — grumpy, precise, allergic to excuses.\n\n{objective} needs supplies he may not have.",
    preChoiceNpc: { speaker: "QM Sgt. Pike", line: "You want miracles or you want what's on the manifest?" },
    choices: [
      {
        id: "manifest",
        label: "\"What's on the manifest.\"",
        role: "commander",
        dialogueLine: "Manifest only. No speeches.",
        npcReply: "Honest. Rare. Here.",
        outcomeText: "Rations and bandages. Not enough. Enough.",
        effects: [{ op: "mod_resource", key: "foodDays", delta: 2 }, { op: "mod_resource", key: "medkits", delta: 1 }],
      },
      {
        id: "favor",
        label: "\"A favor for a favor.\"",
        role: "gunner",
        dialogueLine: "We scratched your truck last week. Square it?",
        npcReply: "Fine. Don't make it habit.",
        outcomeText: "Extra mags. Debt logged.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: 2 }, { op: "mod_all_constitution", delta: -2 }],
      },
      {
        id: "walk",
        label: "\"We'll make do.\"",
        role: "loader",
        dialogueLine: "We'll make do.",
        npcReply: "Most of you do. Some don't.",
        outcomeText: "Empty hands. Full pride.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 4 }],
      },
    ],
  },
  gen2_npc_field_hospital_nun: {
    id: "gen2_npc_field_hospital_nun",
    kind: "npc_conversation",
    atmosphere: "Ether and hymns behind canvas walls.",
    narrative: "Field hospital — nun sorting morphine by candlelight.\n\nWounded from {objective} will end up here.",
    preChoiceNpc: { speaker: "Sister Marie", line: "You bring me patients or you bring me silence?" },
    choices: [
      {
        id: "donate",
        label: "\"Two medkits for your table.\"",
        role: "loader",
        dialogueLine: "Two kits. Use them on our boys if needed.",
        npcReply: "God bless the generous.",
        outcomeText: "Kits handed over. Morale up.",
        effects: [{ op: "mod_resource", key: "medkits", delta: -2 }, { op: "mod_all_constitution", delta: 6 }],
      },
      {
        id: "ask",
        label: "\"Any news from the line?\"",
        role: "commander",
        dialogueLine: "What are you hearing from the line?",
        npcReply: "Men who talk too much lose legs. Be careful.",
        outcomeText: "Warning taken. Silence kept.",
        effects: [{ op: "mod_constitution", role: "commander", delta: 4 }],
      },
      {
        id: "go",
        label: "\"We can't stay.\"",
        role: "driver",
        dialogueLine: "Column's moving.",
        npcReply: "Then go. Drive careful.",
        outcomeText: "Canvas fades. War returns.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 2 }],
      },
    ],
  },
  gen2_npc_deserter_german: {
    id: "gen2_npc_deserter_german",
    kind: "npc_conversation",
    atmosphere: "Hands up. Uniform too clean for the ditch.",
    narrative: "German deserter — wants water, not glory. Intel on {objective} maybe.\n\nPrisoner policy is simple until it isn't.",
    preChoiceNpc: { speaker: "Prisoner (Klaus)", line: "Water. No tricks. I tell you what the road ahead looks like." },
    choices: [
      {
        id: "water",
        label: "\"Water for directions.\"",
        role: "commander",
        dialogueLine: "Water first. Talk second.",
        npcReply: "Bridge weak. Armor on the ridge.",
        outcomeText: "Intel traded. Conscience debated.",
        effects: [{ op: "mod_resource", key: "waterCanteens", delta: -1 }, { op: "seed_flag", flag: "gen2_deserter_intel" }],
      },
      {
        id: "mp",
        label: "\"Send him to MP.\"",
        role: "gunner",
        dialogueLine: "MP's problem now.",
        npcReply: "Ja. Better than your gun.",
        outcomeText: "Prisoner marched rearward.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 3 }],
      },
      {
        id: "ignore",
        label: "\"Not our fight.\"",
        role: "loader",
        dialogueLine: "Keep walking.",
        npcReply: "Danke. Maybe.",
        outcomeText: "Man in the ditch. You in the tank.",
        effects: [{ op: "mod_all_constitution", delta: -3 }],
      },
    ],
  },
  gen2_npc_baker_woman: {
    id: "gen2_npc_baker_woman",
    kind: "npc_conversation",
    atmosphere: "Oven still warm in a roofless house.",
    narrative: "Baker woman — bread for cigarettes. {objective} smells like hunger.\n\nCharity or trade.",
    preChoiceNpc: { speaker: "Madame Laurent", line: "Bread for your boys. Price is kindness or smokes." },
    choices: [
      {
        id: "smokes",
        label: "\"Cigarettes for a loaf.\"",
        role: "loader",
        dialogueLine: "Carton for the loaf.",
        npcReply: "Fair. Feed them while it's soft.",
        outcomeText: "Bread shared. Bellies full.",
        effects: [{ op: "mod_resource", key: "foodDays", delta: 2 }, { op: "mod_all_constitution", delta: 5 }],
      },
      {
        id: "thanks",
        label: "\"Thank you, no charge.\"",
        role: "commander",
        dialogueLine: "We pay in protection. Eat.",
        npcReply: "Protection is a big word. Eat anyway.",
        outcomeText: "Gift given. Trust fragile.",
        effects: [{ op: "mod_all_constitution", delta: 4 }],
      },
      {
        id: "decline",
        label: "\"We have rations.\"",
        role: "gunner",
        dialogueLine: "Rations only.",
        npcReply: "Then go. I keep the oven.",
        outcomeText: "No bread. No debt.",
        effects: [{ op: "mod_constitution", role: "gunner", delta: 1 }],
      },
    ],
  },
  gen2_npc_mine_clearer: {
    id: "gen2_npc_mine_clearer",
    kind: "npc_conversation",
    atmosphere: "Probe and wire. Hands that shake after the war.",
    narrative: "Mine clearer team — path to {objective} might be clean. Might be bait.\n\nFollow or find your own way.",
    preChoiceNpc: { speaker: "Cpl. Hess", line: "We swept to the white stake. Past that, you're on God's dice." },
    choices: [
      {
        id: "follow",
        label: "\"Follow your stakes.\"",
        role: "driver",
        dialogueLine: "On your marks, Hess.",
        npcReply: "Slow. Boring. Alive.",
        outcomeText: "Cleared lane. Time spent.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 6 }],
      },
      {
        id: "own",
        label: "\"We'll probe ourselves.\"",
        role: "asst_driver",
        dialogueLine: "We'll probe ahead.",
        npcReply: "Your funeral. Or theirs.",
        outcomeText: "Probes done. Heart rate high.",
        effects: [{ op: "mod_constitution", role: "asst_driver", delta: 2 }, { op: "mod_tank_health", delta: -8 }],
      },
      {
        id: "detour",
        label: "\"Wide detour south.\"",
        role: "commander",
        dialogueLine: "South around the field.",
        npcReply: "Long. Safer maybe.",
        outcomeText: "Detour holds. Mines stay someone else's problem.",
        effects: [{ op: "mod_resource", key: "foodDays", delta: -1 }],
      },
    ],
  },
  gen2_npc_chaplain_tea: {
    id: "gen2_npc_chaplain_tea",
    kind: "npc_conversation",
    atmosphere: "Tea in a tin mug. Steam in cold air.",
    narrative: "Chaplain with a kettle — offers tea before {objective}.\n\nReligion optional. Warmth mandatory.",
    preChoiceNpc: { speaker: "Padre Walsh", line: "Tea first. Prayers if you want them. No invoice either way." },
    choices: [
      {
        id: "tea",
        label: "\"Tea. No sermon.\"",
        role: "gunner",
        dialogueLine: "Tea. Skip the sermon.",
        npcReply: "Sermon's free. Tea's hot.",
        outcomeText: "Heat in hands. Quiet in heads.",
        effects: [{ op: "mod_all_constitution", delta: 7 }],
      },
      {
        id: "pray",
        label: "\"Short prayer.\"",
        role: "commander",
        dialogueLine: "Short one. Men are listening.",
        npcReply: "God knows short.",
        outcomeText: "Words said. Weight shared.",
        effects: [{ op: "mod_all_constitution", delta: 5 }, { op: "mod_constitution", role: "commander", delta: 4 }],
      },
      {
        id: "pass",
        label: "\"Can't stop.\"",
        role: "driver",
        dialogueLine: "Column's rolling.",
        npcReply: "Cup for the road then.",
        outcomeText: "Tea in a canteen. Small mercy.",
        effects: [{ op: "mod_constitution", role: "driver", delta: 3 }],
      },
    ],
  },
  gen2_npc_conversation_mail: {
    id: "gen2_npc_conversation_mail",
    kind: "npc_conversation",
    atmosphere: "Mail sacks and rubber stamps. Names become paperwork.",
    narrative: "Mail clerk — letters for the living, tags for the dead.\n\n{objective} can wait five minutes for humanity.",
    preChoiceNpc: { speaker: "Pvt. Mailer", line: "You want outbound, inbound, or bad news?" },
    choices: [
      {
        id: "out",
        label: "\"Outbound — one letter.\"",
        role: "loader",
        dialogueLine: "One letter. Keep it moving.",
        npcReply: "It'll go. Might get there.",
        outcomeText: "Words sent home. Hope sent with them.",
        effects: [{ op: "mod_constitution", role: "loader", delta: 6 }],
      },
      {
        id: "in",
        label: "\"Any mail for us?\"",
        role: "gunner",
        dialogueLine: "Anything for our names?",
        npcReply: "Two. One's good. One isn't.",
        outcomeText: "Paper cuts deeper than shrapnel.",
        effects: [{ op: "mod_all_constitution", delta: -2 }, { op: "mod_constitution", role: "gunner", delta: 4 }],
      },
      {
        id: "none",
        label: "\"Not today.\"",
        role: "commander",
        dialogueLine: "No mail. No delays.",
        npcReply: "Suit yourself.",
        outcomeText: "Sacks untouched. War continues.",
        effects: [{ op: "mod_constitution", role: "commander", delta: 2 }],
      },
    ],
  },
  gen2_combat_panzerfaust_team: {
    id: "gen2_combat_panzerfaust_team",
    kind: "infantry_combat",
    atmosphere: "Faust tubes in a ditch. Kids with old men's weapons.",
    narrative: "Panzerfaust team — close range, desperate math.\n\n{objective} behind you. Contact now.",
    useDice: true,
    stakes: "elevated",
    stakesNote: "Hull at faust range — loader ready smoke or lead.",
    choices: [
      {
        id: "mg",
        label: "Hull MG sweep — asst driver.",
        role: "asst_driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Trench churns. Tubes silent or not.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -2 }],
      },
      {
        id: "he",
        label: "HE the ditch — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Ditch becomes crater. Costly silence.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
      {
        id: "back",
        label: "Reverse behind berm — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Hull hidden. Fausts frustrated.",
        effects: [{ op: "mod_tank_health", delta: -3 }],
      },
    ],
  },
  gen2_combat_nashorn: {
    id: "gen2_combat_nashorn",
    kind: "tank_combat",
    atmosphere: "Long 88 on a thin hull. Distance is their religion.",
    narrative: "Nashorn — open ground, long gun. {tank} must close or die at range.\n\nAP and nerve.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: -1, label: "Nashorn" },
    stakes: "elevated",
    stakesNote: "First shot belongs to whoever sees first.",
    choices: [
      {
        id: "smoke_close",
        label: "Smoke and close — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Grey screen. Distance eaten.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "snap",
        label: "Snap AP at movement — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Shot goes. Result unknown until metal rings.",
        effects: [{ op: "spend_ammo", ammo: "AP", amount: 2 }],
      },
      {
        id: "hold",
        label: "Hold hull-down — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Patience. They must come or leave.",
        effects: [{ op: "mod_tank_health", delta: -5 }],
      },
    ],
  },
  gen2_combat_bunker_line: {
    id: "gen2_combat_bunker_line",
    kind: "defensive_stand",
    atmosphere: "Concrete lips along the ridge. MG fire stitches the sky.",
    narrative: "Bunker line — {objective} needs the ridge. You need the bunkers dead.\n\nHE, WP, or infantry.",
    useDice: true,
    stakes: "elevated",
    stakesNote: "Crew nerve and ammo both on the table.",
    choices: [
      {
        id: "he",
        label: "HE the embrasures — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Concrete coughs dust. Guns maybe die.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
      {
        id: "wp",
        label: "WP screen and move — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "White smoke. Infantry time.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "infantry",
        label: "Dismount and assault — asst driver.",
        role: "asst_driver",
        modifierBonus: -1,
        choiceRisk: "desperate",
        outcomeText: "Boots up the slope. Metal behind them.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -3 }],
      },
    ],
  },
  gen2_combat_flak_truck: {
    id: "gen2_combat_flak_truck",
    kind: "tank_combat",
    atmosphere: "Flak bursts like black flowers.",
    narrative: "Flak truck on a farm road — air defense turned ground terror.\n\nKill it before {objective} becomes impossible.",
    useDice: true,
    enemy: { idealAmmo: "HE", label: "Flak 38 truck" },
    choices: [
      {
        id: "coax",
        label: "Coax sweep — gunner.",
        role: "gunner",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Truck twitches. Sky clears a little.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -2 }],
      },
      {
        id: "he",
        label: "Main HE — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Truck becomes scrap and flame.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 1 }],
      },
      {
        id: "smoke",
        label: "Smoke past — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Past the kill zone. Ears ringing.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }, { op: "mod_tank_health", delta: -4 }],
      },
    ],
  },
  gen2_combat_assault_gun: {
    id: "gen2_combat_assault_gun",
    kind: "tank_combat",
    atmosphere: "Low profile, big muzzle brake. Stug life.",
    narrative: "StuG III — ambush predator. {tank} trades angle for survival.\n\nSide shot or smoke.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: 0, label: "StuG III" },
    choices: [
      {
        id: "flank",
        label: "Flank wide — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Angle found. Shot window opens.",
        effects: [{ op: "mod_tank_health", delta: -6 }, { op: "spend_ammo", ammo: "AP", amount: 1 }],
      },
      {
        id: "frontal",
        label: "Frontal AP — gunner.",
        role: "gunner",
        modifierBonus: -1,
        choiceRisk: "aggressive",
        outcomeText: "Sparks. Prayers. Maybe a kill.",
        effects: [{ op: "spend_ammo", ammo: "AP", amount: 2 }],
      },
      {
        id: "wp",
        label: "WP and reposition — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Blind them. Move.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
    ],
  },
  gen2_infantry_barn_fight: {
    id: "gen2_infantry_barn_fight",
    kind: "infantry_combat",
    atmosphere: "Hay dust and muzzle flash inside a barn.",
    narrative: "Infantry in a barn — close, loud, wrong for tanks.\n\nDismount or flatten.",
    useDice: true,
    choices: [
      {
        id: "dismount",
        label: "Clear with dismounts — asst driver.",
        role: "asst_driver",
        modifierBonus: 0,
        choiceRisk: "tactical",
        outcomeText: "Doors kicked. Barn quiet.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -3 }],
      },
      {
        id: "he",
        label: "HE through the wall — gunner.",
        role: "gunner",
        modifierBonus: -1,
        choiceRisk: "aggressive",
        outcomeText: "Wall gone. Barn gone. Problem gone.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
      {
        id: "bypass",
        label: "Bypass the barn — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Barn stays angry behind you.",
        effects: [{ op: "mod_tank_health", delta: -5 }],
      },
    ],
  },
  gen2_infantry_haystack_sniper: {
    id: "gen2_infantry_haystack_sniper",
    kind: "infantry_combat",
    atmosphere: "Haystack twitch. One shot, one secret.",
    narrative: "Sniper in hay — {objective} stalled until the twitch stops.\n\nSmoke, rush, or patience.",
    useDice: true,
    choices: [
      {
        id: "burn",
        label: "Burn the stack — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Fire solves the riddle.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "rush",
        label: "Rush the stack — loader.",
        role: "loader",
        modifierBonus: -1,
        choiceRisk: "desperate",
        outcomeText: "Boots charge. Shot or silence.",
        effects: [{ op: "mod_hp", role: "loader", delta: -10 }],
      },
      {
        id: "wait",
        label: "Wait him out — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Sun moves. Sniper breaks or flees.",
        effects: [{ op: "mod_all_constitution", delta: -3 }],
      },
    ],
  },
  gen2_infantry_cellar_grenade: {
    id: "gen2_infantry_cellar_grenade",
    kind: "infantry_combat",
    atmosphere: "Cellar grate rattles. Grenade hunger below.",
    narrative: "Cellar fight — grenades and echoes.\n\nClear for {objective} or seal it.",
    useDice: true,
    choices: [
      {
        id: "frag",
        label: "Frag down the grate — loader.",
        role: "loader",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Thump. Silence. Maybe.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -2 }],
      },
      {
        id: "seal",
        label: "Seal with debris — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Grate buried. Threat buried maybe.",
        effects: [{ op: "mod_tank_health", delta: -2 }],
      },
      {
        id: "ignore",
        label: "Mark and bypass — commander.",
        role: "commander",
        modifierBonus: 0,
        choiceRisk: "tactical",
        outcomeText: "Marked for engineers. You move.",
        effects: [{ op: "seed_flag", flag: "gen2_cellar_marked" }],
      },
    ],
  },
  gen2_infantry_hedgerow_lmg: {
    id: "gen2_infantry_hedgerow_lmg",
    kind: "infantry_combat",
    atmosphere: "Belt-fed talk from the hedgerow.",
    narrative: "MG42 in a hedgerow — bursts that stitch the column.\n\nSuppress or flank for {objective}.",
    useDice: true,
    choices: [
      {
        id: "suppress",
        label: "Suppress with coax — asst driver.",
        role: "asst_driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Green tracers. Heads down.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -2 }],
      },
      {
        id: "flank",
        label: "Flank on foot — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Angle found. Gun dies.",
        effects: [{ op: "mod_hp", role: "gunner", delta: -8 }],
      },
      {
        id: "smoke",
        label: "Smoke and punch through — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Smoke wall. Treads rolling.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }, { op: "mod_tank_health", delta: -6 }],
      },
    ],
  },
  gen2_defensive_88_reverse: {
    id: "gen2_defensive_88_reverse",
    kind: "defensive_stand",
    atmosphere: "Reverse-slope 88. You see muzzle flash before the gun.",
    narrative: "Hidden 88 — reverse slope. {tank} must survive the first kiss.\n\nSmoke, hull-down, or shoot first.",
    useDice: true,
    stakes: "elevated",
    stakesNote: "First hit decides if you keep treads.",
    choices: [
      {
        id: "smoke",
        label: "WP and reposition — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Blind the arc. Move.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "ap",
        label: "AP at the flash — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Shot traded. Someone wins.",
        effects: [{ op: "spend_ammo", ammo: "AP", amount: 2 }],
      },
      {
        id: "hold",
        label: "Hold and pray — driver.",
        role: "driver",
        modifierBonus: -1,
        choiceRisk: "desperate",
        outcomeText: "Impact. Ringing. Maybe living.",
        effects: [{ op: "mod_tank_health", delta: -12 }],
      },
    ],
  },
  gen2_defensive_mortar_rain: {
    id: "gen2_defensive_mortar_rain",
    kind: "defensive_stand",
    atmosphere: "Whine overhead. Earth jumps.",
    narrative: "Mortar rain — bracketed. {objective} far. Survival close.\n\nMove, dig, or smoke.",
    useDice: true,
    choices: [
      {
        id: "move",
        label: "Move after each bracket — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Treads bite. Shells hit empty ground.",
        effects: [{ op: "mod_tank_health", delta: -5 }],
      },
      {
        id: "dig",
        label: "Dig in the crew — loader.",
        role: "loader",
        modifierBonus: 0,
        choiceRisk: "cautious",
        outcomeText: "Scrapes in dirt. Shrapnel whispers.",
        effects: [{ op: "mod_all_constitution", delta: -4 }],
      },
      {
        id: "counter",
        label: "Counter-battery call — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "aggressive",
        outcomeText: "Radio war. Rain slows.",
        effects: [{ op: "mod_all_constitution", delta: 3 }],
      },
    ],
  },
  gen2_defensive_night_probe: {
    id: "gen2_defensive_night_probe",
    kind: "defensive_stand",
    atmosphere: "Night sounds amplified. Metal on metal in the dark.",
    narrative: "Night probe — enemy testing the line before {objective}.\n\nLights, fire, or silence.",
    useDice: true,
    choices: [
      {
        id: "flare",
        label: "Pop flares — gunner.",
        role: "gunner",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Night becomes day. Targets or shadows.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -1 }],
      },
      {
        id: "mg",
        label: "MG into the noise — asst driver.",
        role: "asst_driver",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Tracers stitch dark. Silence returns.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -2 }],
      },
      {
        id: "hold",
        label: "Hold fire — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Discipline. Fear. Alive.",
        effects: [{ op: "mod_all_constitution", delta: 4 }],
      },
    ],
  },
  gen2_offensive_orchard_push: {
    id: "gen2_offensive_orchard_push",
    kind: "offensive_assault",
    atmosphere: "Trees splinter. Fruit and shrapnel mix.",
    narrative: "Orchard assault — {objective} beyond the last row.\n\nPush loud or push smart.",
    useDice: true,
    choices: [
      {
        id: "push",
        label: "Push with HE — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Trees fall. Resistance falls maybe.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
      {
        id: "infantry",
        label: "Infantry lead — asst driver.",
        role: "asst_driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Boots first. Tank second.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -2 }],
      },
      {
        id: "slow",
        label: "Slow advance — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Row by row. Costly time.",
        effects: [{ op: "mod_tank_health", delta: -4 }],
      },
    ],
  },
  gen2_offensive_barn_assault: {
    id: "gen2_offensive_barn_assault",
    kind: "offensive_assault",
    atmosphere: "Barn doors open like a mouth.",
    narrative: "Barn assault — defenders inside. {objective} needs the farm clear.\n\nBreaching choices.",
    useDice: true,
    choices: [
      {
        id: "breach",
        label: "Breach with HE — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Splinters and silence.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 1 }],
      },
      {
        id: "infantry",
        label: "Infantry clear — loader.",
        role: "loader",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Rooms cleared. Hands shaking.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -3 }],
      },
      {
        id: "bypass",
        label: "Bypass barn — commander.",
        role: "commander",
        modifierBonus: 0,
        choiceRisk: "cautious",
        outcomeText: "Barn stays hot behind you.",
        effects: [{ op: "mod_tank_health", delta: -7 }],
      },
    ],
  },
  gen2_offensive_ridge_charge: {
    id: "gen2_offensive_ridge_charge",
    kind: "offensive_assault",
    atmosphere: "Skyline close. Everyone shoots at silhouettes.",
    narrative: "Ridge charge — {objective} on the far slope.\n\nSpeed is armor until it isn't.",
    useDice: true,
    choices: [
      {
        id: "charge",
        label: "Charge the skyline — driver.",
        role: "driver",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Treads hammer earth. Crest taken.",
        effects: [{ op: "mod_tank_health", delta: -10 }, { op: "mod_constitution", role: "driver", delta: 5 }],
      },
      {
        id: "smoke",
        label: "Smoke then climb — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Grey ridge. Fewer eyes.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "fire",
        label: "Fire support then move — gunner.",
        role: "gunner",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Slope softened. Advance costly anyway.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
    ],
  },
  gen2_combat_king_tiger_far: {
    id: "gen2_combat_king_tiger_far",
    kind: "tank_combat",
    atmosphere: "Mass at extreme range. The road feels smaller.",
    narrative: "King Tiger — far engagement. {tank} is not built for this weight class.\n\nSmoke, shoot, or hide.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: -2, label: "King Tiger" },
    stakes: "critical",
    stakesNote: "Outgunned at range — crew must agree before the trigger.",
    choices: [
      {
        id: "smoke",
        label: "WP screen — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "White wall. Buy meters.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 2 }],
      },
      {
        id: "ap",
        label: "AP at the glacis — gunner.",
        role: "gunner",
        modifierBonus: -2,
        choiceRisk: "desperate",
        outcomeText: "Sparks on kings. Prayers in English.",
        effects: [{ op: "spend_ammo", ammo: "AP", amount: 3 }],
      },
      {
        id: "withdraw",
        label: "Withdraw to hull-down — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Reverse. Live to argue.",
        effects: [{ op: "mod_tank_health", delta: -8 }],
      },
    ],
  },
  gen2_combat_stuhturm: {
    id: "gen2_combat_stuhturm",
    kind: "tank_combat",
    atmosphere: "Assault gun in urban rubble. Alley becomes a barrel.",
    narrative: "StuH in rubble — alley fight. {objective} one block away.\n\nClose fight rules.",
    useDice: true,
    enemy: { idealAmmo: "HE", label: "StuH 42" },
    choices: [
      {
        id: "he",
        label: "HE around the corner — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Rubble becomes more rubble.",
        effects: [{ op: "spend_ammo", ammo: "HE", amount: 2 }],
      },
      {
        id: "infantry",
        label: "Dismount clear — asst driver.",
        role: "asst_driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Brick dust and breath.",
        effects: [{ op: "mod_resource", key: "smallArmsMags", delta: -2 }],
      },
      {
        id: "back",
        label: "Back out — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Alley abandoned. Pride wounded.",
        effects: [{ op: "mod_tank_health", delta: -5 }],
      },
    ],
  },
  gen2_combat_pak_ambush_road: {
    id: "gen2_combat_pak_ambush_road",
    kind: "tank_combat",
    atmosphere: "PAK in a culvert. First shot is a lecture.",
    narrative: "PAK ambush — culvert flash. {tank} must survive the lesson.\n\nSmoke, shoot, or sprint.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: -1, label: "PAK 40" },
    choices: [
      {
        id: "smoke",
        label: "Smoke the culvert — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Grey out the tube.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 1 }],
      },
      {
        id: "ap",
        label: "AP through the face — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Muzzle flash traded.",
        effects: [{ op: "spend_ammo", ammo: "AP", amount: 2 }],
      },
      {
        id: "ram",
        label: "Ram speed past — driver.",
        role: "driver",
        modifierBonus: -1,
        choiceRisk: "desperate",
        outcomeText: "Speed as armor. Scrape and gone.",
        effects: [{ op: "mod_tank_health", delta: -14 }],
      },
    ],
  },
  gen2_elite_night_tiger: {
    id: "gen2_elite_night_tiger",
    kind: "elite_encounter",
    atmosphere: "Green optics. Heavy treads. Night belongs to cats.",
    narrative: "Tiger I at night — eyes that see heat you do not have.\n\n{objective} can wait one minute for survival.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: -2, label: "Tiger I (night)" },
    stakes: "critical",
    stakesNote: "Night fight vs heavy armor — ammo and nerve burn fast.",
    choices: [
      {
        id: "wp",
        label: "WP blind — gunner.",
        role: "gunner",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "White sun. Target lost or found.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 2 }],
      },
      {
        id: "ap",
        label: "AP at muzzle flash — gunner.",
        role: "gunner",
        modifierBonus: -1,
        choiceRisk: "aggressive",
        outcomeText: "Flash traded. Metal screams.",
        effects: [{ op: "spend_ammo", ammo: "AP", amount: 3 }],
      },
      {
        id: "hold",
        label: "Hold fire — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Discipline. Tiger hunts elsewhere.",
        effects: [{ op: "mod_all_constitution", delta: 3 }],
      },
    ],
  },
  gen2_elite_jagdtiger_stub: {
    id: "gen2_elite_jagdtiger_stub",
    kind: "elite_encounter",
    atmosphere: "Mass without a turret. The road bends around fear.",
    narrative: "Jagdtiger rumor — maybe hull-down, maybe myth.\n\n{objective} behind this nightmare.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: -3, label: "Jagdtiger" },
    stakes: "critical",
    stakesNote: "If it is real, you are not winning a fair fight.",
    choices: [
      {
        id: "smoke",
        label: "Smoke and flank — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Grey geometry. Side maybe open.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 2 }],
      },
      {
        id: "call",
        label: "Call for air — commander.",
        role: "commander",
        modifierBonus: 0,
        choiceRisk: "cautious",
        outcomeText: "Radio prayer. Jets maybe.",
        effects: [{ op: "mod_all_constitution", delta: 4 }],
      },
      {
        id: "run",
        label: "Run the gauntlet — driver.",
        role: "driver",
        modifierBonus: -2,
        choiceRisk: "desperate",
        outcomeText: "Treads screaming. Luck louder.",
        effects: [{ op: "mod_tank_health", delta: -18 }],
      },
    ],
  },
  gen2_elite_king_tiger_close: {
    id: "gen2_elite_king_tiger_close",
    kind: "elite_encounter",
    atmosphere: "Close enough to read zimmerit. Far enough to die.",
    narrative: "King Tiger close — alley ambush. {tank} is a toy in the shadow.\n\nOnly angles save you.",
    useDice: true,
    enemy: { idealAmmo: "HEAT", combatMod: -2, label: "King Tiger" },
    stakes: "critical",
    stakesNote: "Side shot or funeral.",
    choices: [
      {
        id: "heat",
        label: "HEAT at flank — gunner.",
        role: "gunner",
        modifierBonus: 0,
        choiceRisk: "aggressive",
        outcomeText: "Shape charge kisses. Result unknown.",
        effects: [{ op: "spend_ammo", ammo: "HEAT", amount: 2 }],
      },
      {
        id: "smoke",
        label: "Smoke and reverse — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Grey alley. Treads backward.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 2 }, { op: "mod_tank_health", delta: -6 }],
      },
      {
        id: "bait",
        label: "Bait for arty — commander.",
        role: "commander",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Coordinates sent. Clock starts.",
        effects: [{ op: "mod_all_constitution", delta: 2 }],
      },
    ],
  },
  gen2_elite_elefant: {
    id: "gen2_elite_elefant",
    kind: "elite_encounter",
    atmosphere: "No turret. No mercy. Road becomes a kill lane.",
    narrative: "Elefant — static predator on a forest road.\n\n{objective} beyond the beast.",
    useDice: true,
    enemy: { idealAmmo: "AP", combatMod: -2, label: "Elefant" },
    stakes: "critical",
    stakesNote: "Frontal is suicide. Geometry is religion.",
    choices: [
      {
        id: "flank",
        label: "Flank through trees — driver.",
        role: "driver",
        modifierBonus: 1,
        choiceRisk: "tactical",
        outcomeText: "Trees scrape. Angle found.",
        effects: [{ op: "mod_tank_health", delta: -8 }, { op: "spend_ammo", ammo: "AP", amount: 2 }],
      },
      {
        id: "wp",
        label: "WP in the optics — gunner.",
        role: "gunner",
        modifierBonus: 1,
        choiceRisk: "cautious",
        outcomeText: "Blind the giant.",
        effects: [{ op: "spend_ammo", ammo: "WP", amount: 2 }],
      },
      {
        id: "withdraw",
        label: "Withdraw and report — commander.",
        role: "commander",
        modifierBonus: 0,
        choiceRisk: "cautious",
        outcomeText: "Alive to tell the truth.",
        effects: [{ op: "mod_all_constitution", delta: 5 }, { op: "journal", text: "Spotted Elefant — lived.", kind: "moment" }],
      },
    ],
  },
};

export const WAVE16_POOL_KIND_BUCKETS: Partial<PoolKindBuckets> = {
  travel: [
    "gen2_travel_orchard_lane",
    "gen2_travel_sunken_road",
    "gen2_travel_pontoon_queue",
    "gen2_travel_signal_cabin",
    "gen2_travel_cattle_on_road",
    "gen2_travel_demolished_church",
    "gen2_travel_forest_gap",
  ],
  supply: [
    "gen2_supply_river_ford",
    "gen2_supply_wire_roll",
    "gen2_supply_oil_drum",
    "gen2_supply_field_phone",
    "gen2_supply_grave_markers",
  ],
  human: [
    "gen2_human_trench_mirror",
    "gen2_human_bootlaces",
    "gen2_human_prayer_card",
    "gen2_human_map_pin",
  ],
  npc: [
    "gen2_npc_regimental_band",
    "gen2_npc_quartermaster_grump",
    "gen2_npc_field_hospital_nun",
    "gen2_npc_deserter_german",
    "gen2_npc_baker_woman",
    "gen2_npc_mine_clearer",
    "gen2_npc_chaplain_tea",
    "gen2_npc_conversation_mail",
  ],
  combat: [
    "gen2_combat_nashorn",
    "gen2_combat_bunker_line",
    "gen2_combat_flak_truck",
    "gen2_combat_assault_gun",
    "gen2_combat_king_tiger_far",
    "gen2_combat_stuhturm",
    "gen2_combat_pak_ambush_road",
  ],
  infantry: [
    "gen2_combat_panzerfaust_team",
    "gen2_infantry_barn_fight",
    "gen2_infantry_haystack_sniper",
    "gen2_infantry_cellar_grenade",
    "gen2_infantry_hedgerow_lmg",
  ],
  defensive: [
    "gen2_defensive_88_reverse",
    "gen2_defensive_mortar_rain",
    "gen2_defensive_night_probe",
  ],
  offensive: [
    "gen2_offensive_orchard_push",
    "gen2_offensive_barn_assault",
    "gen2_offensive_ridge_charge",
  ],
  elite: [
    "gen2_elite_night_tiger",
    "gen2_elite_jagdtiger_stub",
    "gen2_elite_king_tiger_close",
    "gen2_elite_elefant",
  ],
};

export function applyWave16PoolRegistration(): string[] {
  return registerTier2PoolKinds(WAVE16_POOL_KIND_BUCKETS);
}
